### ISSUE TITLE
Create an option to pick up all items at once from your corpse

### ISSUE THREAD

**Issue by GiggySmalls** [henkelmax/corpse#1]
I am always frustrated when I have to first go over the top bar and move the items into my hotbar and then take all the remaining items one by one.

The option to take all items at once with the top bar going into your hotbar (if possible) and the remaining items in your inventory.

**Comment by henkelmax** [comment]
The update should be available in a few minutes.
Let me know if it works.

**Comment by GiggySmalls** [comment]
We are still on version 1.16.1 while we wait for the other mods to catch up. I see you have added it in the 1.16.2 version.

**Comment by henkelmax** [comment]
It should now also be available in 1.16.1.

**Comment by GiggySmalls** [comment]
Thank you! I will get back to you in a few minutes to let you know if it works :)

**Comment by GiggySmalls** [comment]
Works like a charm, thank you so much!

**Comment by henkelmax** [comment]
No problem!

**Comment by BluePhoenix0120** [comment]
i need it for 1.12.2
