### ISSUE TITLE
[1.16.3] Client crash when trying to access a players death history with /deathistory name

### ISSUE THREAD

**Issue by WhitePhant0m** [henkelmax/corpse#10]
**Bug description**
title

**Steps to reproduce the issue**
1. have a player die
2. do /deathhistory playername
3. crash

**Expected behavior**
no crash

**Log files**
[Crash Log](https://paste.gg/p/wphant0m/393d48f0107544509073f2dfbe16c911)

**Versions**
- Minecraft version 1.16.3
- Forge version 34.1.24
- Mod version 1.1.2

**Other mods**
Listed in the crash log

**Comment by WhitePhant0m** [comment]
As an addition to this, [failing to open a corpse](https://paste.gg/p/wphant0m/302a7f3e2f8e43b8b3b798ca76d3c22b)

**Comment by henkelmax** [comment]
Do you have any custom translations?

> java.lang.IllegalArgumentException: Illegal pattern character 'f'

This crash is caused when the translation of `gui.corpse.death_history.date_format` is no valid [date format](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html).

I added a fallback if the translation is not valid, but you should check your Minecraft instance.

In the next version I added a log output that shows the actual translation of the date format. 

So if you update to the next version, please send me your logs again.

---

> As an addition to this, [failing to open a corpse](https://paste.gg/p/wphant0m/302a7f3e2f8e43b8b3b798ca76d3c22b)

Unfortunately I am not able to reproduce this issue.
Can you send me the contents of your `deaths` folder in your world directory?

**Comment by WhitePhant0m** [comment]
[deaths.zip](https://github.com/henkelmax/corpse/files/5415123/deaths.zip)
f064374d-dcd8-402a-bdd8-3b0e2b9d8259 is the UUID of the player whose inventory we weren't able to open.
I don't think I have custom translations.

**Comment by WhitePhant0m** [comment]
I can confirm that the crash no longer happens tho 👍

**Comment by WhitePhant0m** [comment]
Not being able to open the death inv also seems to happen with my inv too, f83bd929-fbf0-4186-becb-658d676fcc42, the inv i'm unable to open is the largest one
https://paste.gg/p/wphant0m/7a75366069dd42878f95bf1d2269bbeb

**Comment by henkelmax** [comment]
The open inventory issue should now be fixed.

---

> I can confirm that the crash no longer happens tho 👍

> This crash is caused when the translation of gui.corpse.death_history.date_format is no valid date format.

Can you send me the complete logs of your client when using version `1.16.3-1.1.3` or newer?
I just added a fallback if the date formatting throws an error, but I added a log message that should show the cause of the issue.
You just have to open the death history GUI once. This logs the translation of this string.

**Comment by WhitePhant0m** [comment]
https://paste.gg/p/wphant0m/f20bc68312354af9abcf419551aeb500

**Comment by henkelmax** [comment]
> [21Oct2020 13:41:21.154] [Render thread/ERROR] [corpse/]: Failed to create date format. This indicates a broken translation: 'gui.corpse.death_history.date_format' translated to yyyy/MM/dd HH:mm:ss

That's weird... It behaves exactly like it should, but throws an exception nevertheless.

I'll have to further investigate this, but it should work for you anyways.
