### ISSUE TITLE
Player Persistence

### ISSUE THREAD

**Issue by keanine** [henkelmax/corpse#105]
This could work as a config option, however it may be better suited as its own mod, but I get the feeling you could reuse some of your code for it and I would like to pitch it to you.

It would be really cool if there was player persistence like in some survival games such as Rust. For example, when you logout the "corpse" entity would spawn, containing the usual item data plus player health. When the player logs back on, the items and health are synced with the corpse entity and then the corpse is despawned. If the entity were to "die" while the player was offline it wouldn't disappear. The player would load in, sync health and items with the entity, despawn the entity and then die.

**Comment by henkelmax** [comment]
https://www.curseforge.com/minecraft/mc-mods/persistent-players
