### ISSUE TITLE
Deaths not in history with baubles equipped.

### ISSUE THREAD

**Issue by CyaniideDrive** [henkelmax/corpse#106]
**Bug description**
When dying with baubles equipped your death does not appear in the death history.

**Steps to reproduce the issue**
1. Equip any bauble.
2. Die.

**Expected behaviour**
I expected the death to be in my history.

**Log files**
There's nothing useful in the log, all it says is that I died with nothing else around it.
**Versions**
- Minecraft version 1.18.2
- Forge version 40.1.73
- Mod version 1.0.1

**Other mods**
There are 262 mods total in the pack, in order to not clutter the report itself I'll comment the list instead.

**Comment by CyaniideDrive** [comment]
3dskinlayers-forge-1.4.6-mc1.18.2
abnormals_delight-1.18.2-3.0.1
AdvancementPlaques-1.18.2-1.4.5.1
AE2-Things-1.0.3-beta
AE2WTLib-11.1.4
AI-Improvements-1.18.2-0.5.0
AkashicTome-1.5-20
alexsdelight-1.18.2-1.3.2
alexsmobs-1.18.6
AmbientEnvironment-forge-1.18.2-7.0+19
angelring-1.18.2-2.0.2
appleskin-forge-mc1.18.2-2.4.1
appliedenergistics2-11.1.6
Applied-Mekanistics-1.2.1
Aquaculture-1.18.2-2.3.8
architectury-4.9.83-forge
armorpointspp-forge-1.18.2-3.0.1
art_of_forging-1.5-1.18.2
artifacts-1.18.2-4.0.7
AttributeFix-Forge-1.18.2-14.0.2
AutoRegLib-1.7-53
balm-3.2.0+0
baubley-heart-canisters-1.18.2-1.0.0
berry_good-1.18.2-5.0.0
BetterAdvancements-1.18.2-0.2.1.132
BetterVillage-Forge-1.18.2-1.0.2
BiomesOPlenty-1.18.2-16.0.0.109-universal
BloodMagic-1.18.2-3.2.6-41
blueprint-1.18.2-5.4.3
Bookshelf-Forge-1.18.2-13.2.47
Botania-1.18.2-435
Buddycards-1.18.2-3.2.1
buzzier_bees-1.18.2-4.0.0
caelus-forge-1.18.1-3.0.0.2
camera-1.18.2-1.0.2
catalogue-1.6.2-1.18.2
cfm-7.0.0-pre29-1.18.2
chat_heads-0.6.1-forge-1.18.2
Chimes-1.1.2-1.18.2
ChiselsBits-forge-1.18.2-1.2.113-universal
citadel-1.11.3-1.18.2
"Clay WorldGen-1.18.2-1.4.0"
climbladdersfast-2.2.2-1.18-forge
cloth-config-6.2.62-forge
Clumps-forge-1.18.2-8.0.0+15
CNB-1.18.2-1.4.0
CodeChickenLib-1.18.2-4.1.1.462-universal
cofh_core-1.18.2-1.6.4.21
collective-1.18.2-4.50
comforts-forge-1.18.2-5.0.0.4
CommonCapabilities-1.18.2-2.8.2
compactmachines-4.5.0
configured-1.5.4-1.18.2
connectedglass-1.1.4-forge-mc1.18
constructionwand-1.18.2-2.7
Controlling-forge-1.18.2-9.0+22
convenientcurioscontainer-1.2-1.18
cookingforblockheads-forge-1.18.2-12.0.2
CoppersDelight-1.18.2-1.4
corail_woodcutter-1.18.2-2.3.6
corpse-1.18.2-1.0.1
CosmeticArmorReworked-1.18.2-v2
craftingtweaks-forge-1.18.2-14.0.3
CraftPresence-1.18.2-Release-1.8.11-universal
Crated_Vanilla_Foods_1.1-1.18.2
create-1.18.2-0.5.0.d
createaddition-1.18.2-20220817a
createcafe-1.9.3-1.18.2
create-confectionery1.18.2_v1.0.8
createdeco-1.2.9-1.18.2.disabled
createfa-1.18.2_v1.0.10.disabled
create-factory-1.18.2-v1.6
CreativeCore_FORGE_v2.6.15_mc1.18.2
CTM-1.18.2-1.1.5+5
Cucumber-1.18.2-5.1.2
culturaldelights-1.18.2-0.13
curios-forge-1.18.2-5.0.7.1
curious-armor-stands-1.18.1-4.0.0
curiouslanterns-1.18.2-1.1.0
curiouslights-forge-1.2.0+1.18.2
Cyclic-1.18.2-1.7.7
CyclopsCore-1.18.2-1.16.0
DarkUtilities-Forge-1.18.2-10.0.5
deathbackup_1.18.2-1.6
"Decorative Blocks-forge-1.18.2-2.1.1"
Delightful-1.18.2-2.0
dimdungeons-166-forge-1.18.2
"Display Case-forge-1.18.2-1.0.2"
domum_ornamentum-1.18.2-1.0.50-ALPHA-universal
DripSounds-1.18-0.3.0
druidcraftrg-0.0.12
DungeonsArise-1.18.2-2.1.50d-beta
dynamiclights-1.18.6
dynamiclightsreforged-1.18.2_v1.3.3
dynview-1.18.2-2.8
eerreforged-1.18.2-1.0.1
EnchantmentDescriptions-Forge-1.18.2-10.0.8
EnderStorage-1.18.2-2.9.0.182-universal
endertanks-1.18-1.11.7
engineersdecor-1.18.2-1.1.24
enhanced_mushrooms-forge-4.0.1+1.18.2
entityculling-forge-mc1.18-1.5.1
EquipmentCompare-1.18.1-1.2.12
expandability-6.0.0
ExperienceBugFix-1.18-1.38.0.2
ExtremeReactors2-1.18.2-2.0.51
extremesoundmuffler-3.28_forge-1.18.2
Fallingleaves-1.18.2-1.3.2
FarmersDelight-1.18.2-1.1.2
FarmersRespite-1.18.2-1.3.0
farsight-1.18.2-1.9
FastFurnace-1.18.2-6.0.3
FastLeafDecay-28
feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2
ferritecore-4.2.1-forge
FluxNetworks-1.18.2-7.0.7.8
flywheel-forge-1.18.2-0.6.5
forbidden_arcanus-1.18.2-2.0.0
ForgeEndertech-1.18.2-9.0.5.0-build.1061
ftbbackups2-forge-1.18.2-1.0.13
ftb-chunks-forge-1802.3.6-build.147
ftb-library-forge-1802.3.6-build.140
ftb-teams-forge-1802.2.6-build.51
ftb-ultimine-forge-1802.3.3-build.55
geckolib-forge-1.18-3.0.36
geode-1.0.7
GeodeOPlenty-1.0.0
getittogetherdrops-1.18.2-1.2
Gobber_Delight_1.0.2_Forge_1.18.2
Gobber2-Forge-1.18.2-2.6.32
goprone-1.18.2-1.7.0
grimoire_of_tetra-1.2.2
Iceberg-1.18.2-1.0.44
ImmersiveEngineering-1.18.2-8.2.0-151
industrial-foregoing-1.18.2-3.3.1.4-8
industrializedcreate1.18.2_1.2.1
infernal-expansion-1.18.2-2.5.0
InfernalGeode-BETA
ironchest-1.18.2-13.1.9
ironfurnaces-1.18.2-3.3.1
IronJetpacks-1.18.2-5.1.4
ItemPhysic_v1.4.23_mc1.18.2
jei-1.18.2-9.7.1.255
journeymap-1.18.2-5.9.0beta2-forge
JustEnoughProfessions-1.18.2-1.2.2
JustEnoughResources-1.18.2-0.14.1.171
Kiwi-1.18.2-forge-6.1.2
largemeals-1.18.2-1.0
lazydfu-1.0-1.18+
libnonymous-2.1.0
LibraryFerret-Forge-1.18.2-2.5.1
LibX-1.18.2-3.2.18
lostcities-1.18-5.3.8
macawsbridgesbop-1.18.2-1.1
macawsbridgesbyg-1.18.2-1.1
macawsroofsbop-1.18.2-1.0
macawsroofsbyg-1.18.2-1.0
Mantle-1.18.2-1.9.27
mcjtylib-1.18-6.0.16
mcw-bridges-2.0.3-mc1.18.2
mcwbridgesabnormals-1.18.2-1.0
mcw-doors-1.0.7-mc1.18.2
mcw-fences-1.0.6-mc1.18.2
mcwfencesbop-1.18.2-1.4
mcwfencesbyg-1.18.2-1.3
mcw-furniture-3.0.1-mc1.18.2
mcw-lights-1.0.4-mc1.18.2
mcw-paintings-1.0.4-mc1.18.2
mcw-paths-1.0.1-mc1.18.2
mcw-roofs-2.1.2-mc1.18.2
mcw-trapdoors-1.0.7-mc1.18.2
mcw-windows-2.0.3-mc1.18.2
Mekanism-1.18.2-10.2.5.465
MekanismGenerators-1.18.2-10.2.5.465
mightyarchitect-mc1.18.2_v0.6
mob_grinding_utils-1.18.2-0.4.44
modnametooltip-1.18.1-1.18.0
Morph-o-Tool-1.5-32
MouseTweaks-forge-mc1.18-2.21
mutil-1.18.2-4.5.0
MysticalAgradditions-1.18.2-5.1.2
MysticalAgriculture-1.18.2-5.1.1
MythicBotany-1.18.2-2.1.12
NaturesAura-36.2
NaturesCompass-1.18.2-1.9.7-forge
neapolitan-1.18.2-3.0.0
netherportalfix-forge-1.18-9.0.0
NethersDelight-1.18.2-2.2.0
nether-s-exoticism-1.18.2-1.1.10
notenoughanimations-forge-1.6.0-mc1.18.2
OceanFloor-1.18.2-1.1.0
Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.3
OpenLoader-Forge-1.18.2-12.0.1
OptiFine_1.18.2_HD_U_H7.disabled
out_of_sight-1.18.2-1.0.2
oxidized-1.18.2-1.1
Patchouli-1.18.2-71.1
PickUpNotifier-v3.2.0-1.18.2-Forge
PigPen-Forge-1.18.2-8.0.1
Placebo-1.18.2-6.6.3
platforms-1.18-1.9.5
pollen-forge-1.4.9+1.18.2
polylib-forge-1801.0.2-build.13
polymorph-forge-1.18.2-0.44
PuzzlesLib-v3.3.5-1.18.2-Forge
Quark-3.2-358
QuarkOddities-1.18
redstonepen-1.18.2-1.0.10
reliquary-1.18.2-2.0.12.1143
repurposed_structures_forge-5.1.14+1.18.2
rsgauges-1.18.2-1.2.16
Runelic-Forge-1.18.2-11.0.1
savage_and_ravage-1.18.2-4.0.0
scannable-1.18.2-forge-1.7.6+135af8a
selene-1.18.2-1.17.9
"Serene Seasons-1.18.2-7.0.0.13"
shetiphiancore-1.18-3.10.10
shutupexperimentalsettings-1.0.5
signpost-1.18.2-2.00.5
simplylight-1.18.2-1.4.2-build.31
smarterfarmers-1.18.2-1.6.0
smoothboot-mc1.18.2-1.0.1
Snad-1.18.2-1.22.04.15a
sophisticatedbackpacks-1.18.2-3.18.17.680
sophisticatedcore-1.18.2-0.5.1.98
soundphysics-forge-1.18.2-1.0.6
Statues-1.18.2-0.1.8.1
StorageDrawers-1.18.2-10.2.1
supplementaries-1.18.2-1.4.12
sworddisplay-1.18.2-1.0.0
TCIntegrations-1.18.2-2.0.13.0
TConstruct-1.18.2-3.5.1.31
TerraBlender-forge-1.18.2-1.1.0.102
tetra-1.18.2-4.9.3
tetrapak-1.18.2-0.5.2
the_bumblezone_forge-5.1.2+1.18.2
theoneprobe-1.18-5.1.1
thermal_cultivation-1.18.2-1.6.3.11
thermal_expansion-1.18.2-1.6.3.13
thermal_foundation-1.18.2-1.6.3.28
thermal_innovation-1.18.2-1.6.3.12
thermal_integration-1.18.2-1.6.3.7
thermal_locomotion-1.18.2-1.6.3.8
"Tinkers Reforged 1.18.2-1.1.0"
titanium-1.18.2-3.5.6-38
ToastControl-1.18.2-6.0.3
ToolBelt-1.18.2-1.18.8
TravelersTitles-1.18.2-Forge-2.1.1
tumbleweed-1.18-0.4.12
twilightforest-1.18.2-4.1.1397-universal
valhelsia_core-forge-1.18.2-0.4.0
viescraftmachines-1.18.2-1.2.0
VisualWorkbench-v3.3.0-1.18.2-Forge
waystones-forge-1.18.2-10.1.0
YungsApi-1.18.2-Forge-2.0.8
YungsBetterDesertTemples-1.18.2-Forge-1.3.1
YungsBetterDungeons-1.18.2-Forge-2.1.0
YungsBetterMineshafts-1.18.2-Forge-2.2
YungsBetterStrongholds-1.18.2-Forge-2.1.1
YungsBetterWitchHuts-1.18.2-Forge-1.0.1
YungsBridges-1.18.2-Forge-2.1.0
YungsExtras-1.18.2-Forge-2.1.0
ZeroCore2-1.18.2-2.1.23

**Comment by henkelmax** [comment]
Can you test if this happens just with corpse and baubles installed?

**Comment by CyaniideDrive** [comment]
I just went to test it with just Corpse, Baubles, and Artifacts (so there was a bauble equipped) and the death history and corpse creation worked fine.
I'll try and find the specific log but when I died in the log all that happened was "CyanSauce has died." And nothing about corpse creation or the like.

**Comment by CyaniideDrive** [comment]
I went back into the overloaded modpack and tested something other than the Curio and the problem was Quark's totem of holding.

**Comment by henkelmax** [comment]
Yeah, these 2 features obviously don't work with each other.
