### ISSUE TITLE
Make Corpses Return the Player UUID

### ISSUE THREAD

**Issue by Raycoms** [henkelmax/corpse#107]
**Is your feature request related to a problem? Please describe.**

Corpse mods don't work well with permission systems, if you die in someone else's claim you don't have access to your corpse.

**Describe the solution you'd like**

Similar to fakeplayers, if corpses have the player UUID, this might work.

**Describe alternatives you've considered**
- Some other generic way to get access to the player UUID that doesn't require specific mod support.

**Additional context**

**Comment by henkelmax** [comment]
The players UUID is stored inside the corpse. But changing the entity UUID to the players UUID is not possible.
