### ISSUE TITLE
Corpse inventory error

### ISSUE THREAD

**Issue by KyrDerz** [henkelmax/corpse#108]
**Please read the [FAQ](https://modrepo.de/minecraft/corpse/faq) before submitting a bug report!**

**Bug description**
When I do not have enough inventory on me to receive every item from the corpse, the menu turns into this.

**Expected behavior**
Keep the previous menu

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version
- 1.18.2
- Forge version
- 40.1.79
- Mod version
- 1.0.2

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/110685473/189503302-e59be5e5-0474-405b-9c85-d4c0f0a00ef1.png)

**Comment by henkelmax** [comment]
Yes, this is completely intended.
