### ISSUE TITLE
 Objects can be multiplied

### ISSUE THREAD

**Issue by Valentin1234a** [henkelmax/corpse#109]
**Bug description**
You can multiply the objects, in practice when one dies the body is put with the objects inside the inventory but if one presses U and takes the objects from there without going to the body he can take them, but the objects remain in the body anyway. .. So one can take the items 2 times. I suggest removing the button to grab items from the guide which is opened with the U button.

**Steps to reproduce the issue**
1. Open 'Chat and write /kill (name)'
2. Click on 'Open the gui with U and click on items and press take items'
3. Go to the body and take the items for the second time ...

**Versions**
- 1.16.5
- Last
- corpse-1.16.5-1.0.6.jar

**Other mods**
I don't think there is a problem caused by other mods

**Comment by henkelmax** [comment]
This is only possible if you are in creative mode.

![image](https://user-images.githubusercontent.com/13237524/190899658-b9203352-a752-4ff5-8721-a808697a9196.png)

That's how it looks if you are in survival
