### ISSUE TITLE
dying in the nether bug

### ISSUE THREAD

**Issue by Sabizos** [henkelmax/corpse#11]
**Bug description**
whenever i die in the nether my death beacon or skull and crossbones is where i died but the corpse isnt. i made a hard save before and was able to reproduce it 4 times. also when i try in the overworld or even dying while in the portal back my corpse appears in the overworld
**Steps to reproduce the issue**
nether
2. Click on '...'
die?
3. Scroll down to '...'
?
where body should be only a thing that says "last death"

**Expected behavior**
i expected to find my body...

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

ok every time i try to drop the death and crash logs onto gist it says "move file here top see preview but when i paste them over and push "create public gist it claims it cant be empty iv attached screen shots 
![Screenshot 2020-10-21 133500](https://user-images.githubusercontent.com/73254956/96782991-3e8d2800-13a2-11eb-8575-b470b3d83ce0.png)
![Screenshot 2020-10-21 133500](https://user-images.githubusercontent.com/73254956/96783242-4fd63480-13a2-11eb-9316-dd34d6d9963d.png)

**Versions**
- Minecraft version
- Forge version
optiforge 16.3
- Mod version
latest
**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

**Screenshots (Optional)**
(mod list is in picture form)
![mod list](https://user-images.githubusercontent.com/73254956/96776759-4fd43580-139e-11eb-821e-f140e9852ec5.png)

i dont understand why you wont let ppl just copy the logs here why add this obtuse system???

**Comment by henkelmax** [comment]
> whenever i die in the nether my death beacon or skull and crossbones is where i died but the corpse isnt.

This death beacon is most likely from `Xaeros Minimap`.

---

> Forge version
> optiforge 16.3

OptiForge is a mod.
There is no version 16.3

---
> Mod version
> latest

Version 1.0.5 isn't the latest version.
Please always provide the exact version.

---

> ok every time i try to drop the death and crash logs onto gist it says "move file here top see preview but when i paste them over and push "create public gist it claims it cant be empty iv attached screen shots

I need logs to identify the problem. Alternatively you can use https://paste.ubuntu.com/ or any other pastebin.

---

> i dont understand why you wont let ppl just copy the logs here why add this obtuse system???

It is better to have the logs properly formatted. 
Log files are usually very large. This just spams the issue section.

---

> It would be ideal if you could test if this problem persists when no other mod is installed.
> If not, please narrow down the mod(s) that are causing the problem.

Have you done that? 
I am not able to reproduce your issue with no other mods installed.

**Comment by henkelmax** [comment]
It seems that the issue is caused by [Ice and Fire](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons).

See this issue: https://github.com/Alex-the-666/Ice_and_Fire/issues/3019
