### ISSUE TITLE
How can an Op/Owner find another player's corpse?

### ISSUE THREAD

**Issue by ejm554** [henkelmax/corpse#111]
I'm a server owner, and I'm trying to help another player (who is currently offline) find their corpse. Is it possible for me to locate it? I looked for documentation and tried commands that might help me, but I came up dry.

I see that I have a `/deathhistory` command available to me, but I'm not sure what mod that is a part of, or if it is a vanilla feature I'm unfamiliar with. It doesn't seem to work, however, since it looks like it may only work for online players.

**Comment by henkelmax** [comment]
The command also takes a UUID of an offline player.

**Comment by ejm554** [comment]
> The command also takes a UUID of an offline player.

Is the `/deathhistory` command part of this mod? Is it documented?

**Comment by henkelmax** [comment]
> Is the /deathhistory command part of this mod? 

Yes

> If so, is it documented?

No, but it should be self explaining.

**Comment by ejm554** [comment]
> No, but it should be self explaining.

I don't think it is self-explaining. :-)

**Comment by henkelmax** [comment]
You enter the command with the player as an argument and it shows the players death history. Thats it.
