### ISSUE TITLE
Cant access corpse Decursio Project version 25

### ISSUE THREAD

**Issue by DarkDon** [henkelmax/corpse#121]
**Please read the [FAQ](https://modrepo.de/minecraft/corpse/faq) before submitting a bug report!**

**Bug description**
I died and after that i could not access my corpse, even deathhistory gives no access to the corpse, cant remove the corpse

**Steps to reproduce the issue**
Dont know if it can be reproduced

**Expected behavior**
right click on corpse open up inventory gui to take out items

**Log files**

**Versions**
- 1.16.5
- 36.2.34
- The Decursio Project - Expert Pre Release 25 

**Other mods**
![23fdd4697a21367066d9224dedd283c2](https://user-images.githubusercontent.com/41093026/213932372-482049e2-dc84-45d4-9921-1b059779048a.png)

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Please provide logs like stated in the template.

**Comment by DarkDon** [comment]
Never mind it was my instance of minecraft who was bugged out. your mod seems fine sorry for bothering you
