### ISSUE TITLE
The Hordes fix

### ISSUE THREAD

**Issue by TANTRUM27X** [henkelmax/corpse#125]
Not sure if problem is with this mod or "The Hordes" mod by smileycorp.

If in the Hordes mod you have the option for a 'player zombie' to spawn when you are killed, I will not leave a corpse.

This makes sense that it wouldn't right away because that zombie has all your loot. Yet, after killing the zombie I thought maybe it would create a corpse as its supposed to be a copy of your character.

I understand its not likely a simple as I put it but if possible I'd love you see them work together.

Game 18.2
Forge 40.1.84
"The Hordes" mod version 1.18.2-1.1.5b
"Corpse" mod version 1.18.2-1.0.1

Just these two mods to produce the issue.

Edit: I read this again and saw it was poorly written and added corrections so you may better understand. Sorry for messaging when I was too tired to proof read.

**Comment by TANTRUM27X** [comment]
I also messaged the owner of the other mod as I'm not sure what end the fix will be on but I hope one/the two of you can find a solution!

**Comment by henkelmax** [comment]
Sorry, but 1.18.2 is no longer actively developed/supported
