### ISSUE TITLE
I got crash when hovering mouse over the arrow in corpse inventory

### ISSUE THREAD

**Issue by IshimaKudzi** [henkelmax/corpse#127]
Steps to reproduce:
1.Hover mouse over arrow at top-right side of corpse inventory.

I got this bug then sort usefull/less items in corpse inventory.

Log
[https://gist.github.com/IshimaKudzi/830e241ad8ed579c1a5121bcc2fcf8c4](url)

Versions
- MInecraft 1.19.3
- Forge 44.1.23
- Corpse 1.0.2

Mods
Installed mods are in the log

**Comment by henkelmax** [comment]
Thanks for reporting this issue

**Comment by IshimaKudzi** [comment]
I need to update Minecraft to 1.19.4 to fix this? lol

**Comment by henkelmax** [comment]
> I need to update Minecraft to 1.19.4 to fix this? lol

No?

**Comment by IshimaKudzi** [comment]
I just don't have to move the mouse over the arrow? XD

**Comment by henkelmax** [comment]
> I just don't have to move the mouse over the arrow? XD

I really don't get what you mean. The fix is available for 1.19.3 and 1.19.4.

**Comment by IshimaKudzi** [comment]
Oh, thx, I reloaded the site but version 1.19.3 did not appear

**Comment by henkelmax** [comment]
https://www.curseforge.com/minecraft/mc-mods/corpse/files/4454605
