### ISSUE TITLE
Add Waila check before trying call it's metheds?

### ISSUE THREAD

**Issue by SegoItCh** [henkelmax/corpse#128]
**Bug description**
Waila method error

**Steps to reproduce the issue**
Die and go to corpse I guess

**Expected behavior**
No errors

**Log files**
(https://paste.gg/p/anonymous/a1e61ea72b20411ab4fb1b59ab807b66)

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.2.39
- Mod version 1.16.5-1.0.6

**Comment by henkelmax** [comment]
1.16.5 is not supported anymore.
