### ISSUE TITLE
Totem Of Corpse

### ISSUE THREAD

**Issue by AltezaR** [henkelmax/corpse#129]
`Is your feature request related to a problem? Please describe.`

This innovation will give the mod a more vanilla minecraft.

`Describe the solution you'd like`

Create «Totem Of Corpse». If the player has it in their inventory, then a corpse with items will be created, and the totem will disappear. It will not be necessary to hold it in your hand.

`Describe alternatives you've considered`

Two options for the implementation of the totem:
1) Like the totem of immortality, it will drop from mobs, but more often and from several.
2) Create a crafting recipe, for example: bones, lapis lazuli and a chest.

`Additional context`

[https://i.imgur.com/dIcJVo1.png](url)

**Comment by henkelmax** [comment]
There are already other mods that have similar mechanics. This mod was made, so you can never accidentally lose your items. This would completely go against that philosophy.
