### ISSUE TITLE
Kick of my server when i open the deathhistory 

### ISSUE THREAD

**Issue by ElTarquin** [henkelmax/corpse#131]
**Bug description**
When i open death history on my server, the server kicks me https://gyazo.com/831136f9f086c54e8d7293bf26cc76d2

**Steps to reproduce the issue**
1. Go to 'deathhistory '
2. server kicks me https://gyazo.com/831136f9f086c54e8d7293bf26cc76d2 (there are nothing in the console of my server, just i've lost connection)

**Log files**
nothing related to corpse mod about my issue

**Versions**
- Minecraft version: 1.19.3
- Forge version:1.19.3 - 44.1.23
- Mod version:[[1.19.3] Corpse 1.19.3-1.0.3] and [1.19.3] Corpse 1.19.3-1.0.2]

**Other mods**
https://gyazo.com/b6df1d6c93241f9cda867f684b10e77b
https://gyazo.com/57f9b4f8bab499a2032b3fc11e34c60a

**Screenshots (Optional)**
https://gyazo.com/831136f9f086c54e8d7293bf26cc76d2

**Comment by henkelmax** [comment]
Please provide your logs and a copy of your `deaths` folder in your world folder.

**Comment by henkelmax** [comment]
Closed due to inactivity.
