### ISSUE TITLE
Incompatibility with Create

### ISSUE THREAD

**Issue by KazuMurako** [henkelmax/corpse#132]
**Bug description**
When a player is killed by a deployer no corpse is spawned and items are destroyed. Death also does not appear when running the /deathhistory command.

**Steps to reproduce the issue**
1. Install Create, Flywheel, and Corpse.
2. Place and power a Deployer and use a wrench on it to set it to attack mode.
3. Take damage from it until you die.

**Expected behavior**
A corpse:corpse entity should be created containing all the items the player had in their inventory upon death, and the death should be saved by the /deathhistory command.

**Log files**
https://pastebin.com/uQWDzyaS

**Versions**
-Operating System: Windows 10 Pro
- Minecraft version: 1.18.2
- Forge version: 40.2.0
- Mod version: 1.0.1

**Other mods**
Create [create-1.18.2-0.5.0.i.jar](https://www.curseforge.com/minecraft/mc-mods/create/files/4371807)
Flywheel [flywheel-forge-1.18.2-0.6.8.a.jar](https://www.curseforge.com/minecraft/mc-mods/flywheel/files/4341461)

**Video**
https://streamable.com/6lh92t

**Additional Context**
I have created an Issue on the Create Github https://github.com/Creators-of-Create/Create/issues/4675

**Comment by henkelmax** [comment]
Does the same thing happen with other mods that process deaths?
Are the items of the player dropping if the corpse mod is not installed?
