### ISSUE TITLE
adaptive_performance_tweaks [items]

### ISSUE THREAD

**Issue by ImpureKin** [henkelmax/corpse#134]
Hi :)

I've recently installed a mod by the name of "Adaptive Performance Tweak [items]" which I believe is deleting corpses that drop with a lot of items in a distance that is far from the player when they respawn (e.g. Nether). In this mod's config, there's the following: https://prnt.sc/spVQNyaqs_OS

Is there any known value that I may be able to place in here / are there any other workarounds that are known? Thought I'd try my luck here before removing the performance mod.

Thanks!

**Comment by henkelmax** [comment]
You'll have to ask the authors of that mod.

**Comment by norfaremc** [comment]
corpse:corpse that's the value you'd put in I believe
