### ISSUE TITLE
Different corpse models for players on server

### ISSUE THREAD

**Issue by Schummel-8** [henkelmax/corpse#135]
**Bug description**
I have a server where i use the mod in a minigame. I have the config set, so the corpse is turned instantly into a skeleton so nobody knows whos corpse it is. I also have set the despawn time to 1000000 seconds so it will never despawn (corpse are killed after each round).
The problem is, that different players see different models for the corpse. The killed player sees the corpse correctly as a skeleton, but the other players see the skin of the player or just a steve/alex skin.

**Steps to reproduce the issue**
1. Go on a server
2. kill a player
3. the player themself sees the skeleton, anybody else most likely sees the normal skin of the dead player on the corpse

**Expected behavior**
Every player should only see a skeleton at every time.

**Log files**
https://gist.github.com/Schummel-8/ca0427fc89b397d0874378a6e8c5385f

**Versions**
- Minecraft version: 1.19.2
- Forge version: 1.19.2-43.2.3
- Mod version: 1.19.2-1.0.0

**Other mods**
No other mods were used.

**Screenshots (Optional)**
https://prnt.sc/KFaZOO29k1MM
https://prnt.sc/rJKQdD34htDo

**Comment by henkelmax** [comment]
Please send me your config

**Comment by Schummel-8** [comment]
Here ist the server config
https://gist.github.com/Schummel-8/d5d6ac55771295bb631d709437990f31

**Comment by henkelmax** [comment]
Does it work with `skeleton_time` set to something like 20?

**Comment by Schummel-8** [comment]
Yes, that solves the problem, thank you!
