### ISSUE TITLE
Game crashed while Rendering screen

### ISSUE THREAD

**Issue by ItsNebb** [henkelmax/corpse#137]
**Bug description**
Every time I try and open my death history, the game crashes with the same error, "Game crashed while Rendering screen".
Was playing with corpse installed for a few days now with no issues, but loaded up RLCraft today and any time I open the death history, even on a new world, the game crashes, any help would be appreciated! thanks.
edit: I also tried doing a fresh install of forge, rlcraft, and only putting in corpse mod, and the issue is still present

**Steps to reproduce the issue**
Die
Open Death History
*Game Crashes*

**Expected behavior**
The Death History screen should open, with no issues and allow me to see coordinates and items of previous deaths.

**Log files**
https://gist.github.com/ItsNebb/869ec221158089d3ccb32def536e7282#file-gistfile1-txt
https://gist.github.com/ItsNebb/1781a822081bafb3bec72c4b3bfb8c92#file-gistfile1-txt (fresh install crash logs)

**Versions**
- 1.12.2
- 0.226.1.1 (most recently updated version of forge)
- 1.12.2

**Other mods**
List of all mods: https://legacy.curseforge.com/minecraft/modpacks/rlcraft/relations/dependencies
OptiFine 1.12.2 HD

Screenshot: https://imgur.com/a/dQWcG9F

**Comment by henkelmax** [comment]
This version is very old and isn't supported anymore.
