### ISSUE TITLE
Causes serious problems with Soul Bound

### ISSUE THREAD

**Issue by Dr-WeiAL** [henkelmax/corpse#140]
**Please read the [FAQ](https://modrepo.de/minecraft/corpse/faq) before submitting a bug report!**

**Bug description**
When using any mod that allows a player's item to not be affected by death drops, it will cause the player's item to simply disappear
This problem is not present in the single player game, it appears in the server side

**Steps to reproduce the issue**
1. Use Soul Bound enchantment or [Mom's Love](https://www.curseforge.com/minecraft/mc-mods/moms-love) to let players die without dropping items
2. Death
3. Then the player's item disappears

**Expected behavior**
It should not disappear
It should go back to the player

**Log files**
https://pastebin.com/i3Q0T6Eg

**Versions**
- Minecraft version 1.19.2
- Forge version 43.2.11
- Mod version 1.0.0

**Other mods**
AttributeFix-Forge-1.19.2-17.2.6
curios-forge-1.19.2-5.1.4.1
l2archery-1.2.5
l2artifacts-1.7.3
l2backpack-1.8.5
l2complements-1.4.7
l2library-1.9.7
l2weaponry-1.2.4
MaxHealthFix-Forge-1.19.2-8.0.1
MomLove-Forge-1.19.2-1.2.0

**Screenshots (Optional)**
![image](https://github.com/henkelmax/corpse/assets/47446553/cf11f78b-b16f-4bce-b171-b5afe3446e0d)
![image](https://github.com/henkelmax/corpse/assets/47446553/8a8ac315-9170-4e3d-a635-274827ad3f8c)
![image](https://github.com/henkelmax/corpse/assets/47446553/fd1c2cb4-0259-47d7-8b69-7054b31eb60f)

![image](https://github.com/henkelmax/corpse/assets/47446553/fabd2928-737f-442e-8612-0a2c8c80e5de)
![image](https://github.com/henkelmax/corpse/assets/47446553/680b9d8a-6835-436b-a4fd-503584f4a829)
![image](https://github.com/henkelmax/corpse/assets/47446553/29083993-de90-444b-8efe-68ea4d6f09cd)

**Comment by henkelmax** [comment]
Looks like these mods don't properly implement their handling of dropping/not dropping the items on death.
This mod just uses Forges LivingDropsEvent (https://github.com/henkelmax/corelib/blob/211d2ec174ae952e22fbab77c47ca0576cdbcf06/src/main/java/de/maxhenkel/corelib/death/DeathEvents.java#L44). If the item is in there it would technically be dropped.

**Comment by lcy0x1** [comment]
I’m the author of the soul bound enchantment mod. I do use LivingDropsEvent and I specifically made sure it worked with Corpse. I will check again.

Here is my implementation 
https://github.com/Minecraft-LightLand/L2Complements/blob/ee4e6433783c96dd296b11171eb29f0f7d892e83/src/main/java/dev/xkmc/l2complements/events/MagicEventHandler.java#L75

**Comment by lcy0x1** [comment]
Yes I double checked. It works. This problem should be caused by other mods that interfere with living drop event.

**Comment by Dr-WeiAL** [comment]
It seems to be a problem with arclight

**Comment by henkelmax** [comment]
> It seems to be a problem with arclight

Yeah we don't support hybrid servers
