### ISSUE TITLE
are you thinking about fabric ports?

### ISSUE THREAD

**Issue by bananaOHHHOOOOHAHAHAHAAAAHA** [henkelmax/corpse#141]
sorry if youve been asked this before. really awesome mod btw. anyways, are you thinking of porting to fabric? sorry to bother you

**Comment by henkelmax** [comment]
Yes, people ask me about that every day and its very annoying. I won't port this mod to Fabric.

**Comment by Krocodile55** [comment]
aw man, I really like this mod but I also like being able to use shaders :(
