### ISSUE TITLE
corpses not spawning when they should

### ISSUE THREAD

**Issue by DIRECTVIRUS** [henkelmax/corpse#167]
**Bug description**
corpse does not spawn at death location leading to item loss.

**Steps to reproduce the issue**
1. die at a location
2. go to location where you died
3. corpse is not at location
4. items you had are lost due to corpse not spawning

**Expected behavior**
corpse should be present at death location with all of your items.

**Log files**
https://gist.github.com/DIRECTVIRUS/5b765bb60fa9e6ed8cc320ca454f3a8b

**Versions**
- minecraft 1.20.1
-  forge 47.2.0 (pack)
- forge 47.1.47 (server)
- mod version: 1.0.5

**Other mods**

server list:
adaptive_performance_tweaks_core_1.20.1-9.1.0.jar
adaptive_performance_tweaks_gamerules_1.20.1-9.1.0.jar
adaptive_performance_tweaks_items_1.20.1-9.1.0.jar
adaptive_performance_tweaks_player_1.20.1-9.1.0.jar
adaptive_performance_tweaks_spawn_1.20.1-9.1.0.jar
AI-Improvements-1.20-0.5.2.jar
alexsmobs-1.22.6.jar
architectury-9.1.12-forge.jar
athena-forge-1.20.1-3.1.1.jar
bettervillage-forge-1.20.1-3.2.0.jar
Bountiful-6.0.3+1.20.1-forge.jar
callablehorses-1.20.1-1.3.0.1.jar
canary-mc1.20.1-0.2.7.jar
chipped-forge-1.20.1-3.0.1.jar
Chunky-1.3.92.jar
citadel-2.4.4-1.20.1.jar
cloth-config-11.1.106-forge.jar
Clumps-forge-1.20.1-12.0.0.3.jar
collective-1.20.1-6.66.jar
comforts-forge-6.3.3+1.20.1.jar
create-1.20.1-0.5.1.d.jar
create-confectionery1.20.1_v1.0.9.jar
create-structures-0.1.1-1.20.1-FORGE.jar
create-stuff-additions1.20.1_v2.0.4a.jar
create_enchantment_industry…-create-0.5.1.d-1.2.6.c.jar
cupboard-1.20.1-2.0.jar
curios-forge-5.3.4+1.20.1.jar
dynview-1.20.1-3.9.jar
entityculling-forge-1.6.2-mc1.20.1.jar
FarmersDelight-1.20.1-1.2.3.jar
FastFurnace-1.20.1-8.0.1.jar
FastLeafDecay-31.jar
FastWorkbench-1.20.1-8.0.2.jar
ferritecore-6.0.0-forge.jar
FramedBlocks-9.0.2.jar
ftb-chunks-forge-2001.2.2.jar
ftb-library-forge-2001.1.3.jar
ftb-quests-forge-2001.1.4.jar
ftb-ranks-forge-2001.1.3.jar
ftb-teams-forge-2001.1.4.jar
ftb-xmod-compat-forge-2.0.1.jar
fusion-1.0.5a-forge-mc1.20.jar
guardvillagers-1.20-1.6.1.jar
immersive_paintings-0.6.6+1.20.1-forge.jar
inventorysorter-1.20.1-23.0.1.jar
item-filters-forge-2001.1.0-build.55.jar
Jade-1.20.1-forge-11.6.1.jar
JadeAddons-1.20.1-forge-5.2.0.jar
jei-1.20.1-forge-15.2.0.27.jar
JustEnoughProfessions-forge-1.20.1-3.0.1.jar
JustEnoughResources-1.20.1-1.4.0.238.jar
Kambrik-6.1.1+1.20.1-forge.jar
kotlinforforge-4.5.0-all.jar
letmedespawn-1.1.1.jar
libraryferret-forge-1.20.1-4.0.0.jar
limitedchunks-1.20.1-3.9.jar
lootr-1.20-0.7.30.73.jar
mcw-bridges-2.1.1-mc1.20.1forge.jar
mcw-doors-1.1.0forge-mc1.20.1.jar
mcw-fences-1.0.7-mc1.20.1forge.jar
mcw-trapdoors-1.1.1-mc1.20.1forge.jar
memoryleakfix-forge-1.17+-1.1.2.jar
modernfix-forge-5.7.5+mc1.20.1.jar
NaturesCompass-1.20.1-1.11.2-forge.jar
observable-4.4.0.jar
Placebo-1.20.1-8.3.7.jar
polymorph-forge-0.49.0+1.20.1.jar
PuzzlesLib-v8.0.24-1.20.1-Forge.jar
rechiseled-1.1.3-forge-mc1.20.jar
resourcefullib-forge-1.20.1-2.1.11.jar
simpleafk-1.0.0.jar
sliceanddice-forge-3.1.2.jar
sophisticatedbackpacks-1.20.1-3.18.59.909.jar
sophisticatedcore-1.20.1-0.5.89.425.jar
spark-1.10.53-forge.jar
starlight-1.1.2+forge.1cda73c.jar
Steam_Rails-1.5.1+forge-mc1.20.1.jar
storagedrawers-1.20.1-12.0.2.jar
StrawStatues-v8.0.1-1.20.1-Forge.jar
supermartijn642configlib-1.1.8-forge-mc1.20.jar
supermartijn642corelib-1.1.12a-forge-mc1.20.jar
villagernames-1.20.1-5.2.jar

client list:

https://www.curseforge.com/minecraft/modpacks/create-perfect-world

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Does this also happen without any other mods?

**Comment by Jabhacker** [comment]
yes it does happen without any other mods @henkelmax

**Comment by henkelmax** [comment]
Can you send me the logs of that?

**Comment by henkelmax** [comment]
Closed due to inactivity.

**Comment by Gerpyl11** [comment]
There is a problem, in a single world, a corpse appears as a result of death, but when I upload it to the server, this mod does not seem to work, what could this be related to?
