### ISSUE TITLE
Any way to prevent survival players from seeing their death coordinates? Unfortunately this mod (1.12.2) makes dying in survival a trivial experience.

### ISSUE THREAD

**Issue by roccscout** [henkelmax/corpse#17]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by henkelmax** [comment]
Next time, please fill out the complete feature request template.

I see no point in hiding coordinates, because players can just install a client side minimap that shows the death location.

**Comment by roccscout** [comment]
"I see no point in hiding coordinates" Are you serious? Why not make that an option?
I have lots of friends who know nothing about Journey minimaps or other mods. But they can literally TELEPORT in survival to their dead body.

It's not survival friendly. Good thing the Lootable Bodies mod is a better option than this.

**Comment by henkelmax** [comment]
Seeing coordinates doesn't mean teleporting!

**Comment by roccscout** [comment]
Is there just no simple way to request that players can't see their coordinates when they die?

It's a hardcore survival modpack. It's this simple: I don't want them to see their coordinates when they die, I want them to find their body in a survival fashion.

Is there no way to disable the "U" menu?

**Comment by henkelmax** [comment]
You can set the `death_storage_duration` value to 0

**Comment by roccscout** [comment]
Where is that option?
This is 1.12.2, and there is no serverconfig.

**Comment by henkelmax** [comment]
This option is only available in newer versions.
