### ISSUE TITLE
Carryon dupes items

### ISSUE THREAD

**Issue by Snarfgbz** [henkelmax/corpse#172]
**Bug description**
Whenever you use carryon to pickup a corpse, all the items in the corpse duplicate.

**Steps to reproduce the issue**
1. /kill (or just die) while wearing an Ad astra space suit
2. Pickup corpse with carryon mod (forge 1.19.2)

**Expected behavior**
Items duplicate

**Log files**
(can't find the event in the log files)

**Versions**
1.19.2
forge
43.3.5
1.0.9

**Other mods**
Carryon Corpse (i have noticed that others have had this issue)

**Screenshots (Optional)**
<img width="960" alt="image" src="https://github.com/henkelmax/corpse/assets/152670469/9190b31a-d63a-47d6-b06e-95da1ff1038f">
(I am on mars using Ad astra) (don't mind the skin, forgot to change it)

**Comment by skul360** [comment]
in the config of carry on you can just add the corpse to the black list so you cant pick it up (altho i dont know the id)

**Comment by Snarfgbz** [comment]
The mod creator already made it so you can’t pick-up a corpse in one of the updated versions for 1.19.2. The problem was that I needed the corpse to be picked-up. In the modpack I eventually just got rid of the feature and made it so you didn’t have to retrieve the body.

**Comment by henkelmax** [comment]
Does this also happen in newer versions? (1.20.1, 1.21.1 or 1.21.3)
