### ISSUE TITLE
Crashing/kicked out when using view death history

### ISSUE THREAD

**Issue by CattopyTheWeb** [henkelmax/corpse#173]
**Bug description**
I am playing on an Aternos server (1.20.1) minecraft forge and when I press the U key I get this error and get kicked out.
<img width="932" alt="image" src="https://github.com/henkelmax/corpse/assets/115007754/69e4b0b6-2a5d-43d0-88c7-e66b56c73291">

**Steps to reproduce the issue**
1. Die
2. Click U key
3. crash/get kicked out

**Expected behavior**
Show me my death history

**Log files**
https://gist.github.com/CattopyTheWeb/42ac9d76efe1fb8f5f10b7ec9cf63ecf

**Versions**
- Minecraft version: 1.20.1
- Mod loader: forge
- Mod loader version: 47.2.0 
- Mod version: 1.0.5

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.
I have a lot of mods so if it's necessary I can list them

**Screenshots (Optional)**
Screenshots of the issue.
![image](https://github.com/henkelmax/corpse/assets/115007754/78acf792-905f-4322-bdc7-fb922450376b)

**Comment by CattopyTheWeb** [comment]
I'm playing on a multiplayer server and I'm not the owner.
The thing is, I went into the world border cause I didn't know it can kill you and died there, now I can't open my corps. And even the owner tried using the /death history command but he got the same result as me (getting kicked out with the same error code)

**Comment by henkelmax** [comment]
I can't help you without the death file.

**Comment by henkelmax** [comment]
Closed due to inactivity.
