### ISSUE TITLE
Corpse Fails To Load

### ISSUE THREAD

**Issue by Omnimetatron** [henkelmax/corpse#178]
**Bug description**
Corpse fails to load

**Steps to reproduce the issue**
1. Load MC using latest corpse and neo
2. Crash

**Expected behavior**
Not to crash

**Log files**
https://gist.github.com/Omnimetatron/ad15299fb86f63006fbdd51b59736d4a - Crash Report
https://gist.github.com/Omnimetatron/02841723a9de5e24d298cee58e3e426d - latest.log
https://gist.github.com/Omnimetatron/9e1e7caf4e8d6d0c3008aa870d5186b2 - debug.log

**Versions**
- MC 1.20.4
- Mod loader NeoForge
- Mod loader version 20.4.148
- Mod version 1.0.10

**Other mods**
Tested in pack, failed, so re-tested the load with corpse alone. Still failed.

**Comment by henkelmax** [comment]
This is already fixed with d8d4fc96a1e30646693bf87df046362344afa9c3
