### ISSUE TITLE
Corpse refusing to spawn after death

### ISSUE THREAD

**Issue by wolfopera** [henkelmax/corpse#181]
### Bug description

When someone dies, the Corpse (more often than not) decides to not spawn. I've gone into spectator mode to look but alas, nothing. 

### Minecraft version

1.19.2

### Mod version

1.19.2-1.0.9

### Mod loader and version

Forge 43.4.5

### Steps to reproduce

1. Die from whatever kills me.
2.  Go to where death marker leads me 
3. Check for corpse, which is nowhere to be found
4. Go into spectator mode, try to teleport directly to death coordinates, etc. cords

### Expected behavior

I expected a corpse to be where my death marker is, as that's the purpose of the mod.

(Side note, the site refused to let me use the gist.github pasting, so I used another!)

### Log files

https://mclo.gs/j07QS1Y

**Comment by henkelmax** [comment]
Does this happen without any other mods aswell?
If the corpse spawns in water, it might float away.

**Comment by wolfopera** [comment]
> Does this happen without any other mods aswell? If the corpse spawns in water, it might float away.

Unfortunately, removing half of our mods didn't fix it and we can't remove much anymore because of the amount of people waiting/trying/are on the server actively. The corpse itself is just NOT spawning, it's not a matter of floating away, but someone will die on land, for example, and it just doesn't create a corpse. I can retrieve their items via death history but only an OP can do that and we're not all on at the same time, unfortunately. :(

**Comment by henkelmax** [comment]
You don't need to do it on your main server. I just need to be sure its an actual issue with the mod and not an incompatibility with another mod.

**Comment by JD1099** [comment]
> You don't need to do it on your main server. I just need to be sure its an actual issue with the mod and not an incompatibility with another mod.

I am having this issue as well. I setup a quick test server to run the mod by itself. For me the issue is clearly a mod compatibility issue because the corpse spawned in the test server. if you'd like I can post the server log, but I think its pointless because the mod simply worked so no logs were made about the corpse mod.

Something I noticed on my main server is the corpse mod seems to be not creating the config toml.

**Comment by henkelmax** [comment]
Can you find out which mod is causing the issue?

**Comment by henkelmax** [comment]
Closed due to inactivity.
