### ISSUE TITLE
Conflict with Configurable Death mod

### ISSUE THREAD

**Issue by linkjankens** [henkelmax/corpse#182]
### Bug description

there seems to be something interfering between this mod and Configurable Death mod https://www.curseforge.com/minecraft/mc-mods/configurable-death

For some reason, items will vanish into the ether on death and are not recoverable, but not all the time. I tried looking into the configs and that didn't help. I also tried looking at the mod itself but I can't figure out how to actually look at it properly (all I see are errors) so I can't figure it out 

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.12

### Mod loader and version

neoforge 47.1.103

### Steps to reproduce

1. have inventory in armor slots, hotbar, and inventory
2. die
3. go to corpse
4. randomly not receive all items

### Expected behavior

receive all items

### Log files

no log

**Comment by henkelmax** [comment]
You mentioned errors, but didn't provide any logs. Please provide log files.

**Comment by henkelmax** [comment]
Closed due to inactivity
