### ISSUE TITLE
Sorting Inventory in Corpse Deletes all Items

### ISSUE THREAD

**Issue by generikb** [henkelmax/corpse#184]
### Bug description

If you have both the Corpse Mod and Inventory Sorter https://www.curseforge.com/minecraft/mc-mods/inventory-sorter installed, your stuff will disappear in the corpse if you attempt to sort it.

Why would you do that? I dunno, but someone playing our new modpack did it and reported the issue haha!

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.12

### Mod loader and version

Forge 47.2.20

### Steps to reproduce

1. Have both Corpse and Inventory Sorter installed
2. Have stuff in your inventory
3. Die 🗡️ 
4. Go to your corpse and press the middle button in the corpse inventory to sort it
5. Wonder where all your stuff went :)

### Expected behavior

To either sort the inventory in the corpse, or do nothing.

### Log files

N/A

**Comment by henkelmax** [comment]
You need to exclude this inventory from being able to have it sorted.

**Comment by JoelZBub** [comment]
This can be closed.
 Inventory has been blacklisted in inventorysorter-server.toml and moved to defaultconfigs
