### ISSUE TITLE
Dupe bug found with tfc vessels.

### ISSUE THREAD

**Issue by redstoneguy10ls** [henkelmax/corpse#185]
### Bug description

In terrafirmacraft or tfc for short theres an item called a vessel which has 4 slots and lets you store items in it, you can right click on it in your inventory to take items out of it, if you do that on the death screen accessed by pressing "u" by default you can take the items out of the vessel. But the items will remain on the corpse.

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.12

### Mod loader and version

Forge - 47.2.19

### Steps to reproduce

download both corpse and tfc
put an item into a vessel
have that vessel on your person
die
open the death history screen
click items
right click on the vessel 

### Expected behavior

The expected behavior would be to not have the item taken out as this glitch doesn't work with bundles from vanilla

### Log files

https://gist.github.com/redstoneguy10ls/85884880879dd61a9a0f8cccb7b9dcaf

### Screenshots

https://cdn.discordapp.com/attachments/1230313291822137415/1230317302990245979/2024-04-18_03-37-31.mp4?ex=6632e147&is=66206c47&hm=6069a286ac40528a755153d46587357e4f70fff994d6c5b9c8eda37fd46001cc&

**Comment by henkelmax** [comment]
Please report this issue to their issue tracker. They need to check if they have access to the container to allow taking items out. This is not a bug of the corpse mod.
