### ISSUE TITLE
"Transfer Items" replaces armor with binding curse

### ISSUE THREAD

**Issue by Schummel-8** [henkelmax/corpse#186]
### Bug description

When a player has armor with the curse of binding enchantment and transfers the items of a corpse with the "transfer items" button, the armor of the corpse will unequip the cursed armor, place it in the inventory and equip the armor from the corpse onto the player.

### Minecraft version

1.19.2

### Mod version

1.19.2-1.0.12

### Mod loader and version

Forge 43.2.3

### Steps to reproduce

1. Equip yourself with some armor
2. kill yourself with /kill
3. Give yourself armor with curse of binding and equip it
4. transfer the items (armor) from the corpse with the button
5. curse of binding armor will appear in inventory

### Expected behavior

The armor with curse of binding stays on the player and the armor of the corpse moves into the inventory or stays in the corpse.

### Log files

https://gist.github.com/Schummel-8/6bb8457146f742284054e5f8c828ad1f

**Comment by henkelmax** [comment]
Does this also happen in newer versions?
