### ISSUE TITLE
Conflict with Dragon Survival

### ISSUE THREAD

**Issue by LassieGirl22** [henkelmax/corpse#187]
### Bug description

Whenever you die as a dragon and the corpse spawns, it gets stuck in a crash loop. 

### Minecraft version

1.20.1

### Mod version

corpse-forge-1.20.1-1.0.12.jar

### Mod loader and version

Forge 47.2.0

### Steps to reproduce

1. Play with dragon survival and the corpse mod
2. Create a new world and select the dragon option
3. Die as a dragon
4. Go near the corpse
5. Enter crash loop

### Log files

https://gist.github.com/LassieGirl22/80d4b0507fe0bc29cc719cd61642e6ac

**Comment by henkelmax** [comment]
This seems to be an issue with dragon survival. Can you also report that issue to their issue tracker?

**Comment by henkelmax** [comment]
Closed due to inactivity
