### ISSUE TITLE
Issue on 1.20.1

### ISSUE THREAD

**Issue by PrimordialCat** [henkelmax/corpse#188]
### Bug description

Dying doesn't spawn the corpse and the the command /corpse history doesn't work 

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.12

### Mod loader and version

Fop

### Steps to reproduce

1. Start the world
2. Try dying
3. look for the corpse
4. tried typing /corpsehistory

### Expected behavior

1.20.1 version doesn't work

### Log files

https://gist.github.com/PrimordialCat/750672c27b57e14f13c0d2ef4579b5af

### Screenshots

![image](https://github.com/henkelmax/corpse/assets/170248231/23afb570-0726-4841-82c4-65418fb218e4)

**Comment by henkelmax** [comment]
This command does not exist.
