### ISSUE TITLE
corpse will not appear

### ISSUE THREAD

**Issue by Bennathen** [henkelmax/corpse#190]
### Bug description

when player dies, items drop but no corpse is found. death coords are marked. 'U' option is unusable when key is pressed. mod is used with curseforge and aternos server, player is operator and whitelisted.

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.12

### Mod loader and version

Forge 37.2.0

### Steps to reproduce

Unsure of how to reproduce issue, but will put what happened.
1. launch forge and aternos server
2. log into server
3. die in server
no corpse

### Log files

https://gist.github.com/Bennathen/fd91732a61a8f4ebf52f031e6ad24729

**Comment by henkelmax** [comment]
I can't find any mention of the mod. It seems you don't have it installed.
