### ISSUE TITLE
Incompatibility with Rustic Engineer

### ISSUE THREAD

**Issue by Fiopon** [henkelmax/corpse#192]
### Bug description

Cannot take items from corpse using transfer items button, and items taken by other means produce ghost items when the mod Rustic Engineer installed

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.12

### Mod loader and version

Forge 47.2.32

### Steps to reproduce

1. Install Rustic Engineer mod alongside Corpse mod
2. Die
3. Go to corpse
4. Attempt to take items
5. fail

### Expected behavior

1. Install Rustic Engineer mod alongside Corpse mod
2. Die
3. Go to corpse
4. Attempt to take items
5. succeed

### Log files

https://gist.github.com/Fiopon/d3f850e74b039139886d02fc8173124e

**Comment by henkelmax** [comment]
Does this happen without any other mods installed?

**Comment by Fiopon** [comment]
No, so it must be one of the mods I have interfering with it

**Comment by Fiopon** [comment]
It appears the issue is a conflict with the mod "Rustic Engineer"
https://www.curseforge.com/minecraft/mc-mods/rustic-engineer

**Comment by henkelmax** [comment]
Duplicate of #191
