### ISSUE TITLE
Backpack/Curios items deleted on Creative mod

### ISSUE THREAD

**Issue by GamingGlitchGG** [henkelmax/corpse#193]
### Bug description

Had a full inventory + Artifacts + Travelers Backpack, died unfairly, TP'd in Creative mod cuz I wasn't gonna walk >1000m a second time, transfered items, noticed all my Curios stuff was gone

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.12

### Mod loader and version

Forge 47.2.0

### Steps to reproduce

-Have a corpse in the world that has a full inventory and Curios/Traveler's Backpack
-Be in creative mod
-Go to corpse and transfer items
-Rip the Curios stuff :(

### Expected behavior

Have my full backpack and Artifacts

### Log files

?

### Screenshots

![image](https://github.com/henkelmax/corpse/assets/68930560/54b02c22-c70e-493d-b679-a62db956b466)

**Comment by henkelmax** [comment]
It is not intended to be done in creative mode. If you would walt over items with a full inventory in creative mode, you items would get deleted aswell. This is a vanilla minecraft feature. Just don't use creative mode if you want to keep items.
