### ISSUE TITLE
There is no "corelib" folder in the source code —— 源码中并没有"corelib"文件夹

### ISSUE THREAD

**Issue by Yi-Jian-Zai-Tian-Ya** [henkelmax/corpse#194]
### Bug description

I didn't find any files under the "corelib" folder mentioned in "CorpseEntity" in any of the 1.16.5 and later branches.
我并没有在版本1.16.5及以后的任何一个分支中，发现有在"CorpseEntity"提到的"corelib"文件夹下的任何文件。

I would love to move the new features "One-Click Transfer" and "Armor Slot" from 1.16.5 and later to version 1.12.2, so I set out to try to read the later version source code and try to write a higher version "Corpse" mod that belongs to 1.12.2.
我很希望将1.16.5及更高版本中新增的："一键转移"、"盔甲槽"等功能移动到版本1.12.2，所以我着手尝试阅读高版本源码，试图写出一个属于1.12.2的高版本"Corpse"。

Nowadays, I have encountered the above problem, I hope the author can provide me with some help, thank you!
现如今，我遇到了上述的问题，希望作者可以为我提供一定的帮助，感谢！

### Minecraft version

1.18.1

### Mod version

1.18.1-1.0.5

### Mod loader and version

Forge 39.1.2

### Steps to reproduce

Please see Bug description.
请见BUG描述。

### Log files

null

**Comment by henkelmax** [comment]
The mod version you are referring to is no longer supported. Only 1.19.2, 1.20.1, 1.20.4 and 1.20.6 are supported.
