### ISSUE TITLE
Item disappeared from hotbar after retrieving items from corpse

### ISSUE THREAD

**Issue by Thelegendking** [henkelmax/corpse#195]
### Bug description

Just as the title says, the item in my hotbar in no.2 slot was a bow which got replaced with an item that I had equipped in Curious mod's slot (ring) and the bow just completely disappeared out of existence after clicking on transferring item button on corpse. Doesn't previously item used to get equipped on their own in curious slots after transferring items from corpse why do they drop in player's inventory instead now? why did you change it?

 EDIT: that's the only reason which is motivating me to remove this mod from my modpack cuz it makes my inventory too damn full and also its tedious to equip every single item back to curious slots previous version in 1.16 of corpse were capable of this... otherwise this mod is superb.

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.12

### Mod loader and version

Forge 47.3.0

### Steps to reproduce

1. Get your hotbar full all the 9 slots but no.2 have a bow
2. Equip ring in the ring slot of curious mod (the ring is from Iron's spell mod)
3. **Die**
4. Click transfer item from corpse and tada you lost your most powerful bow from apotheosis mod.

### Expected behavior

Bow gets poofed

### Log files

https://mclo.gs/wLdgt6m

### Screenshots

In the log check after "King was impaled by Marauder" that's when this bug happened.

**Comment by henkelmax** [comment]
#133
