### ISSUE TITLE
player dies and his items were dropped on the floor

### ISSUE THREAD

**Issue by pedrobalafina** [henkelmax/corpse#197]
### Bug description

instead of dying and your items appearing stored in your body, they were dropped on the ground

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.12

### Mod loader and version

Forge 47.3.5

### Steps to reproduce

1. Die

### Log files

https://gist.github.com/pedrobalafina/698bf2ba11bd7892fd42037cd6280233.js

### Screenshots

![image](https://github.com/user-attachments/assets/5c8bfd48-ec34-4e5e-ba32-5bc08e03cb20)

**Comment by henkelmax** [comment]
Your log files are invalid. Please make sure you send the full logs.
Does this happen without any other mods installed?

**Comment by henkelmax** [comment]
Closed due to inactivity.
