### ISSUE TITLE
Compat between Corpse and Gravestone 

### ISSUE THREAD

**Issue by Taknax** [henkelmax/corpse#2]
I tried both mods, but couldnt get work.

My first suggestion: The Gravestone could be generated after the corpse is existing for 15 min. 

My second suggestion: Player and entity corpse gets lootable. By rightclicking u can choice wich item u want. it should be disposable, if u dont want take the item.

**Comment by henkelmax** [comment]
I don't plan compatibility between these mods, as they serve the same purpose.

**Comment by Taknax** [comment]
Ty for reply and they are anyway both rly nice mods!

Am Fr., 14. Aug. 2020 um 14:49 Uhr schrieb Max Henkel <
notifications@github.com>:
