### ISSUE TITLE
Item White/Black list for intentional drops

### ISSUE THREAD

**Issue by RedAngel121** [henkelmax/corpse#200]
### Bug description

I am using Lightmans Currency mod and one of the options is that you can drop a portion of coins you have earned on the ground when you die. Currently there is no way to drop those coins and keep the other stuff safe. Could you add a whitelist/blacklist option to either allow or ignore certain items from being automatically stored in the corpse entity?

### Minecraft version

[FORGE][1.20.1] Corpse 1.20.1-1.0.12

### Mod version

[FORGE][1.20.1] Corpse 1.20.1-1.0.12

### Mod loader and version

[FORGE][1.20.1] Corpse 1.20.1-1.0.12

### Steps to reproduce

install Lightmans Currency
get any wallet and some coins
put coins in wallet
`/gamerule coinDropPercent 100` 
_Die_
find dropped coins outside of wallet but still in corpse

### Expected behavior

Lightmans Currency coins should drop on the ground and not be stored in the corpse when CoinDropPercentage is set above zero. 

### Log files

https://mclo.gs/UqM0Lo3

**Comment by henkelmax** [comment]
The mod must implement the death drops properly in order for the corpse to contain the items. If there are items dropped on the ground thats a bug with the mod and noth with corpse.

**Comment by RedAngel121** [comment]
Based on your response, i feel you did not understand the objective i was attempting to portray. 
I dont want coins stored in the corpse and it still picked them up after death when they drop.
the intent is to drop coins and save everything else

**Comment by henkelmax** [comment]
Oh ok, yeah that isn't something I'm planning to add, sorry.
