### ISSUE TITLE
incompat with blueskies (duplication glitch)

### ISSUE THREAD

**Issue by thvless** [henkelmax/corpse#201]
### Bug description

if a player dies while having an arc from blueskies equipped, the item will both drop on the ground and be found inside the corpse, essentially duplicating it

latest.log doesnt really show much of value so i attached debug.log too

### Minecraft version

1.20.1

### Mod version

corpse-forge-1.20.1-1.0.12

### Mod loader and version

Forge 47.2.18

### Steps to reproduce

equip an arc in arcs inventory tab
die
item can be found on the ground where you died and inside the corpse

### Log files

https://gist.github.com/thvless/1545f7420fca8159ede6f75a80e2041d

**Comment by henkelmax** [comment]
I tested it with `blue_skies-1.20.1-1.3.31` and it works perfectly fine.
