### ISSUE TITLE
incompat with blue skies (tested)

### ISSUE THREAD

**Issue by thvless** [henkelmax/corpse#202]
### Bug description

I opened #201 a few days ago and it was closed as perfectly fine, i tested again with only: 
corpse-forge-1.20.1-1.0.12 (latest)
blue_skies-1.20.1-1.3.31 (latest) + its dependency structure_gel-1.20.1-2.16.2
on Forge 47.2.18

Bug is still present.

https://github.com/user-attachments/assets/40df3796-6f46-457f-aa61-d44952d28e83

![Screenshot 2024-08-17 225440](https://github.com/user-attachments/assets/e92ac798-1bc2-498e-868d-2319b7a05f02)

### Minecraft version

1.20.1

### Mod version

1.0.12

### Mod loader and version

Forge 47.2.18

### Steps to reproduce

-

### Expected behavior

-

### Log files

https://gist.github.com/thvless/b6149f2ccd60ebca3a990caead03a20d

**Comment by henkelmax** [comment]
Oh, you didn't tell me that I need to put them into a separate inventory.

That looks like an issue with the blue skies mod. They most likely arent using Forges death events properly, but due to the mod being closed source I am not able to look into the issue or see what causes the issue.
