### ISSUE TITLE
repeated crash

### ISSUE THREAD

**Issue by JurkoDev** [henkelmax/corpse#203]
### Bug description

i just crash
am on a server
i just found that its 19 crashes in a row that were all corpse

i thought it was Apotheosis as that was repeatedly failing  ShieldBreakerTest
heres my main log trimmed cause it was 700mb https://gist.github.com/JurkoDev/643c9f83ec8c189b500b71310fa030d2

[crash-2024-08-25_21.20.36-client.txt](https://github.com/user-attachments/files/16741849/crash-2024-08-25_21.20.36-client.txt)
[crash-2024-08-25_21.29.22-client.txt](https://github.com/user-attachments/files/16741850/crash-2024-08-25_21.29.22-client.txt)
[crash-2024-08-25_21.50.21-client.txt](https://github.com/user-attachments/files/16741851/crash-2024-08-25_21.50.21-client.txt)
[crash-2024-08-25_22.18.41-client.txt](https://github.com/user-attachments/files/16741852/crash-2024-08-25_22.18.41-client.txt)
[crash-2024-08-25_22.23.21-client.txt](https://github.com/user-attachments/files/16741853/crash-2024-08-25_22.23.21-client.txt)
[crash-2024-08-25_17.33.43-client.txt](https://github.com/user-attachments/files/16741854/crash-2024-08-25_17.33.43-client.txt)
[crash-2024-08-25_17.35.53-client.txt](https://github.com/user-attachments/files/16741855/crash-2024-08-25_17.35.53-client.txt)
[crash-2024-08-25_17.46.46-client.txt](https://github.com/user-attachments/files/16741856/crash-2024-08-25_17.46.46-client.txt)
[crash-2024-08-25_17.49.12-client.txt](https://github.com/user-attachments/files/16741857/crash-2024-08-25_17.49.12-client.txt)
[crash-2024-08-25_17.52.48-client.txt](https://github.com/user-attachments/files/16741858/crash-2024-08-25_17.52.48-client.txt)
[crash-2024-08-25_17.59.07-client.txt](https://github.com/user-attachments/files/16741859/crash-2024-08-25_17.59.07-client.txt)
[crash-2024-08-25_18.02.45-client.txt](https://github.com/user-attachments/files/16741860/crash-2024-08-25_18.02.45-client.txt)
[crash-2024-08-25_18.05.36-client.txt](https://github.com/user-attachments/files/16741861/crash-2024-08-25_18.05.36-client.txt)
[crash-2024-08-25_18.53.01-client.txt](https://github.com/user-attachments/files/16741862/crash-2024-08-25_18.53.01-client.txt)

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.12

### Mod loader and version

Forge 47.3.7

### Steps to reproduce

¯\_(ツ)_/¯ idk its just corpses that were there that crash me for some reason now

### Expected behavior

not to crash

### Log files

https://gist.github.com/JurkoDev/643c9f83ec8c189b500b71310fa030d2

**Comment by henkelmax** [comment]
Please update the mod to the latest version. And please also check if this happens without any other mods.

**Comment by JurkoDev** [comment]
> Please update the mod to the latest version. And please also check if this happens without any other mods.

Uh am on the latest 1.20.1 that's on curseforge

**Comment by henkelmax** [comment]
Thats not true.
https://www.curseforge.com/minecraft/mc-mods/corpse/files/5661478

And please check if it happens without any other mods.

**Comment by henkelmax** [comment]
Closed due to inactivity
