### ISSUE TITLE
Crash while looking at another player's corpse

### ISSUE THREAD

**Issue by mxnmnm** [henkelmax/corpse#207]
### Bug description

I was looking at my friend's corpse and clicked to additional items, he transferred the items to his inventory which caused the crash. This happened on a server. I have a lot of other mods so idk if others are interfering in other ways, hopefully not but if it is absolutely needed I can test for that later.

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.14

### Mod loader and version

Forge 47.3.6

### Steps to reproduce

1. Have dedicated server
2. Have two players
3. Have one player die with additional items
4. Have the other player look at the additional items screen
5. Have the other player transfer the items to inventory and crash

### Expected behavior

No crash

### Log files

https://gist.github.com/mxnmnm/99bef08904301b5a50fd1410a73dec3e

**Comment by henkelmax** [comment]
I tried to reproduce it and it works perfectly fine in both server and singleplayer, for different players and the same player. Please check if this happens without any other mods installed.

**Comment by Cpt0range** [comment]
tried to reproduce my self and got it first try
i think you missed the additional items part in the report
i reproduced it with the Artifacts mod
the version is 1.20.1 Forge 47.3.0
The Crashlog:
https://gist.github.com/Cpt0range/39992cf549a692e54274d833eabc9724

**Comment by henkelmax** [comment]
Tried it with additional items and another player on the server and it works perfectly fine.
