### ISSUE TITLE
Corpses Sometimes Do Not Spawn

### ISSUE THREAD

**Issue by UdderlyEvelyn** [henkelmax/corpse#209]
### Bug description

As the title says. I tried the teleport command you mentioned in another issue post, and the corpse truly does not exist. I've also used the teleport command to make sure I was right at the spot, and checked below in case it fell. There was no water in most cases that this happens. It happens maybe 60%+ of the time in my modpack currently. Attached log from play session yesterday where a death occurred in which there was no corpse. I will work with you to figure out which mods are relevant if it will help, I am a developer so feel free to be technical.

### Minecraft version

1.20.1

### Mod version

1.0.14

### Mod loader and version

Forge 47.3.0

### Steps to reproduce

1. Start world.
2. Die
3. Probably No Corpse

### Expected behavior

Corpse.

### Log files

https://gist.githubusercontent.com/UdderlyEvelyn/58fc0146adf195ade0e1d61209a64830/raw/80527a284853fc620073fb54b8d60e4ea0452a62/gistfile1.txt

**Comment by henkelmax** [comment]
Does this happen without any other mods installed?

**Comment by UdderlyEvelyn** [comment]
> Does this happen without any other mods installed?

Very much doubt it, heh. Trying to figure out the incompatibility or interaction. I'll verify, though, when I have time later today.

**Comment by UdderlyEvelyn** [comment]
Yeah doesn't happen without other mods - as expected. Typically in the modpack the deaths that it happens with have been freezing to death via Cold Sweat, so I'll test that in isolation.

**Comment by UdderlyEvelyn** [comment]
Okay so I've found one cause:
https://www.curseforge.com/minecraft/mc-mods/let-me-despawn

That said, I've experienced it without that as well. I'll remove that from my pack and validate whether it happens over a longer period to see if the occurrences are reduced or gone.

**Comment by henkelmax** [comment]
> Actually it seems you can exclude entities from that mod, what is the entity name for the corpse? corpse:corpse?

Yes, that should be the entity ID

**Comment by UdderlyEvelyn** [comment]
Still occuring without that mod present, though far more rarely.

**Comment by UdderlyEvelyn** [comment]
![2024-09-25_19 54 26](https://github.com/user-attachments/assets/dea8500b-ef83-4f09-b661-819b8ca278a3)
Example of me returning to an exact death spot (as confirmed by the death spot tp in the Corpse GUI) to find no corpse.

**Comment by UdderlyEvelyn** [comment]
While checking on that spot I died, went into creative and used the GUI to tp back to the new death spot and even running '/tp @e[type=corpse:corpse,sort=nearest,limit=1]' as mentioned by you in another issue post returned nothing.
![2024-09-25_19 57 28](https://github.com/user-attachments/assets/cd30d94f-0554-4370-9208-aa1eaf8e9531)

**Comment by henkelmax** [comment]
But does it happen without any other mods at all?

**Comment by UdderlyEvelyn** [comment]
I'm well aware that it is a mod interaction - is your position that you just don't support using your mod with other mods at all and it's not your problem? If so, just say that so I can stop submitting data and expecting assistance.

**Comment by UdderlyEvelyn** [comment]
It does not seem to occur with the gravestone mod, which I assume shares much of its code with Corpse. I assume this is due to it being blocks/block entities rather than entities. Just not sure what's messing with the entities of Corpse.

**Comment by henkelmax** [comment]
> I'm well aware that it is a mod interaction - is your position that you just don't support using your mod with other mods at all and it's not your problem? If so, just say that so I can stop submitting data and expecting assistance.

Without you helping me find out the issue, I can't fix it.
Your setup causes the issue and I am not able to reproduce it. Thats why I am asking questions to be able to narrow down the issue. If you are not willing to work with me on this, thats not my problem.

**Comment by UdderlyEvelyn** [comment]
> > I'm well aware that it is a mod interaction - is your position that you just don't support using your mod with other mods at all and it's not your problem? If so, just say that so I can stop submitting data and expecting assistance.
> 
> Without you helping me find out the issue, I can't fix it. Your setup causes the issue and I am not able to reproduce it. Thats why I am asking questions to be able to narrow down the issue. If you are not willing to work with me on this, thats not my problem.

Okay, my apologies then - perhaps I was being assumptive or oversensitive. You already asked me to verify whether it happens with other mods, and it does not. I misread that as you being dismissive since we'd already gone over that point.

As I mentioned, the issue does not happen with the gravestone mod, so I am fairly certain it is specific to entities. I imagine it is either being removed (as the previous mod was causing) or is somehow failing to spawn. I do have mods that cap various entity types, and I am wondering if perhaps if these are at cap it might be preventing the corpse from being created? I wonder if these sorts of interactions might be avoided if the corpse were a blockentity instead of an entity.

I am presently suspecting one of these two mods:
https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-spawn
https://www.curseforge.com/minecraft/mc-mods/spawncapcontrolutility

While I am a developer in general I am not a Minecraft modder (yet), so I am not sure if the corpse entity would be impacted by the caps set in the latter. I will test..

**Comment by UdderlyEvelyn** [comment]
Confirm that adding an exception for the corpse entity to the following mod was the other cause, so we've found two mods that need exceptions or removal for compatibility with Corpse:
https://www.curseforge.com/minecraft/mc-mods/let-me-despawn
https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-spawn

**Comment by henkelmax** [comment]
Id suggest reporting that to them, so they add the exceptions by default. It is also really broken to delete entities, that are not alive (like item frames, etc.) this really sounds like a general bug.
