### ISSUE TITLE
The Aether mod's gloves

### ISSUE THREAD

**Issue by FowlizM** [henkelmax/corpse#210]
### Bug description

Gloves dont stay on the corpse. Well, they do but it doesnt appear as equipped on my inventroy 

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.14

### Mod loader and version

Forge 47.3.7

### Steps to reproduce

1- Equip the mod gloves
2- Die
3- Claim the corpse items
4- Check the glove slot in inventory
5- Admire the bug

### Expected behavior

Glove is supposed to be shown on the armor slot in left side

### Log files

It occurs in a server called silverkeep, discord invite link is same as what i wrote

### Screenshots

![image](https://github.com/user-attachments/assets/8b577718-ea76-41e4-a04b-8f96d430401e)
As it can be seen, theres gloves on my skin in first person view but it doesnt appear on inventory nor 3rd person view
![image](https://github.com/user-attachments/assets/f4b21ad9-d109-4fb1-9c8d-9ce519686894)

**Comment by henkelmax** [comment]
Is the item in the curios inventory?

**Comment by henkelmax** [comment]
Closed due to inactivity.
