### ISSUE TITLE
Corpse in the End

### ISSUE THREAD

**Issue by uhloin** [henkelmax/corpse#211]
### Bug description

Throw Ender Pearls several times in row (without wait falling) between edges of isles above Void. During uncertain condition, may be with combination of falling damage, the position of death appears under the floor of the world. Corpse was not found. Because of hard to reproduce there should be some re-check for such case to create accessible corpse.

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.14

### Mod loader and version

Forge 47.3.7

### Steps to reproduce

Throw Ender Pearls several times in row (without wait falling) between edges of isles above Void.

### Log files

n/a

**Comment by henkelmax** [comment]
Please fill out all fields of the issue template.

Is this reproducible?

**Comment by uhloin** [comment]
I was not able to reproduce it again

**Comment by henkelmax** [comment]
Without it being reproducible, I can't help you, sorry. Please feel free to reopen if you have a way for me to reproduce it in a consistent way.
