### ISSUE TITLE
We cannot respawn and more bug

### ISSUE THREAD

**Issue by iKattor** [henkelmax/corpse#212]
### Bug description

We added the corpse mod to our Mod Packk and after dying a few times in the game, we noticed something, it used to happen sometimes, but then it started to happen all the time, every time we die, the respawn option becomes stuck and we press the main menu and then click respawn, but the character enters the bug, the character is on the ground and red. Sometimes we can't move, sometimes it gets stuck on the back button when respawning. 

**The mod was like this before the update, not because of the new update.**

**Possible Conflicting Mods**
Improvable Skills 3
Epic Fight

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.15

### Mod loader and version

Forge 47.3.0

### Steps to reproduce

1. Play
2. Die
3. Cannot respawn
4. main menu
5. respawn
6. spawn with bug

### Log files

https://gist.github.com/iKattor/87b26e5d9b9bf19cbb5cb8592e76c065

### Screenshots

![2024-10-12 061321](https://github.com/user-attachments/assets/307f1da4-6009-4789-8d9e-f612e5d6a8c6)

**Comment by henkelmax** [comment]
You have a lot of errors from other mods in your logs. Can you check if this happens with just the corpse mod?

**Comment by iKattor** [comment]
ofc, i'm gonna send in 2 days

**Comment by iKattor** [comment]
[latest.log](https://github.com/user-attachments/files/17352622/latest.log)

**Comment by iKattor** [comment]
> You have a lot of errors from other mods in your logs. Can you check if this happens with just the corpse mod?

[latest.log](https://github.com/user-attachments/files/17352625/latest.log)

**Comment by henkelmax** [comment]
You still have a lot of mods installed and errors. I think these are the wrong logs.

**Comment by iKattor** [comment]
> You still have a lot of mods installed and errors. I think these are the wrong logs.

I will find the right one and post it and I will also post a video with that bugs as an extra.

**Comment by henkelmax** [comment]
Closed due to inactivity.
