### ISSUE TITLE
Unable to retrieve items after death

### ISSUE THREAD

**Issue by MildPanda** [henkelmax/corpse#24]
**WAIT. I HAVE READ FAQ AND THIS IS DIFFERENT!**
Version: corpse-1.15.2-1.0.9
Forge Version: forge-1.15.2-31.2.45
Minecraft Version: 1.15.2
I died in the Nether by burning. I was sniped off a tower and then died by burning and couldn't find the body so I entered creative mode and pulled up the death history. When pressing items of my most recent death the console spews out the linked error message. 
https://gist.github.com/MildPanda/a17361e2a2b28e12ffc14e9dbd5b48d0
I tried digging down into the ground to see if it was somehow buried and it wasn't. 
Body didn't go into lava either.
Died by an Afrit from Lycanites Mobs if that helps any but I doubt that'd cause the issue. 
I'll edit this post if I am able to reproduce. 
I'm using [this ](https://www.curseforge.com/minecraft/modpacks/crafttoexiledissonance) modpack with a few extra mods added; Moarboats, Refined storage.

Noticing some of my other deaths I can't open either even though I've reclaimed them.

**Comment by henkelmax** [comment]
Let me know if it works for you.

**Comment by MildPanda** [comment]
That fixed it! Thanks and happy new year.

**Comment by henkelmax** [comment]
> That fixed it! Thanks and happy new year.

Thank you!

> If you've got a location where I can provide a small tip let me know.

Nah its fine :)
