### ISSUE TITLE
Can't open my own corpse with cheats turned off and only owner can acces corpse turned on

### ISSUE THREAD

**Issue by Minothilos** [henkelmax/corpse#26]
**Please read the [FAQ](https://modrepo.de/minecraft/corpse/faq) before submitting a bug report!**

**Bug description**
I changed the server config to "only_owner = true" and "skeleton = true" since I'm intending to play the modpack on a server. Whith these settings I'm unable to open my own corpse in a singleplayer world with cheats turned off (and I'm assuming on a server as a non-op) I can access my corpse just fine in another singleplayer world with the same config but cheats turned on.

**Steps to reproduce the issue**
1. Change the server config to "only_owner = true" and "skeleton = true"
2. Launch game
3. Die with items in inventory
4. Locate corpse

**Expected behavior**
Being able to acces my own corpse after death-

**Log files**
14:29:11.043
Minothilos bled to death from injuries caused by Skeleton
14:29:11.202
[CHAT] Minothilos bled to death from injuries caused by Skeleton
14:29:11.213
[net.diebuddies.physics.PhysicsMod:blockifyEntity:374]: add all: 12
14:29:17.304
SoundControl Sound Processor is lagging; behind 44 msecs
14:29:19.564
SoundControl Sound Processor is lagging; behind 12 msecs

**Versions**
- Minecraft version 1.16.5
- Forge version 36.0.42
- Mod version 1.0.0

**Other mods**
Tried to disable all other mods, same thing still happens

**Screenshots (Optional)**
Screenshots of the issue.
![image](https://user-images.githubusercontent.com/48357207/109419896-0fca3280-79d0-11eb-93ef-642e62827144.png)

**Comment by Minothilos** [comment]
Here's the full serverconfig:
[https://pastebin.com/fVpsbFu9](url)

**Comment by henkelmax** [comment]
Can you please test if this happens on servers?
If it also happens on servers, please try running this command when standing next to the corpse:
`/data get entity @e[type=corpse:corpse,limit=1,sort=nearest]`
Please send me the output of this command and also the UUID of your player: https://mcuuid.net/

**Comment by Minothilos** [comment]
Same thing happens on my server if I'm not op'd
Here's the result of my command:
[https://pastebin.com/KzCamhuk](url)
My UUID is:
b106c313-1ed3-4af0-ac00-f8b84a4d6f0a

**Comment by henkelmax** [comment]
Thank you! I found the issue. It should be fixed very soon.
