### ISSUE TITLE
[Suggestion] Compatibility with Cosmetic Armor Reworked

### ISSUE THREAD

**Issue by SlimF** [henkelmax/corpse#27]
**Is your feature request related to a problem? Please describe.**
If you have items in your Cosmetic Armor slots and die, when you get them back they go to your normal inventory instead of the one from Cosmetic Armor.

**Describe the solution you'd like**
Let's say you have a helmet and a chestplate in your Cosmetic Armor inventory when you die. When you go back to your corpse and take your items, the helmet and chestplate should go to where they were (in the Cosmetic Armor inventory)

**Additional context**
[CurseForge link](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[Github link](https://github.com/zlainsama/CosmeticArmorReworked)

**Comment by henkelmax** [comment]
https://github.com/henkelmax/gravestone/issues/37#issuecomment-772537411
