### ISSUE TITLE
Corpse renders wearable items

### ISSUE THREAD

**Issue by DD12-1916** [henkelmax/corpse#3]
**Is your feature request related to a problem? Please describe.**
No, not really. It is simply a feature request.

**Describe the solution you'd like**
Wearable items such as Armour, Elytra, maybe even Baubles, Wearable Backpacks, or BackTools, are rendered on the corpse instead of just appearing in its inventory. (maybe the corpse can hold weapons and tools too!).
Moreover, it can be taken a step further, by redesigning the item screen to match (or just using) a player's inventory, complete with the armour slots and bauble slots.

**Describe alternatives you've considered**
I haven't really considered any other options, maybe the armour wears the corpse instead.

**Additional context**
Uhhh... the skeleton would obviously wear the armour too and be resurrected and completely obliterate you with its all-new Godly-enchanted weapons. But that obviously is outside the scope for this mod so they'll just stay dead.
Anyway, super awesome mod! It really adds to the immersion of the game.

**Comment by henkelmax** [comment]
Thank you for suggesting this feature.
Let me know if you like it.

**Comment by DD12-1916** [comment]
Woah, that fast? Damn, you are once again awesome, my man. I don't know if it was that easy or not, but that's not the point, props for the quick reply!
I will be testing it once I have finished setting up 1.16.2.

**Comment by henkelmax** [comment]
Thank you!

**Comment by DD12-1916** [comment]
Tested 1.0.5 for a bit just now, and so far, it's working well! Although it seems that corpses don't disappear when you take their items (I believe this is a feature?) unless there are more than two corpses of the player. But the other issue was that tools still render even if you already took the respective item from the corpse inventory screen.
Just some quick observations haha

**Comment by henkelmax** [comment]
Unfortunately, due to limitations in the current way, items in the corpse are stored, it is not possible to remove the equipment when the items are taken out.
The first item taken seems to be a bug.
I will not add modded equipment to the corpse as it would require a lot of dependencies to other mods. And I want to be able to port my mods as soon as possible to newer versions.
Can you explain what doesn't work with the teleport feature?

**Comment by DD12-1916** [comment]
Ohhh okay, and yeah I guess, it would be troublesome to have dependencies to other mods, as that would certainly make the mod feel bloated without any proper reason.
So uh, I may have misunderstood the teleport feature, as I believe that I am wrong in thinking that your character is supposed to be teleported to the location of the death when you click on the coordinates on the death history screen? Or does it just show the coordinates in the chat, where then you could click on it and be given the teleport command to that location? Because the latter works for me; I just remembered it being the former.

**Comment by henkelmax** [comment]
Yes this is exactly what it should do. It was like this back in 1.12

**Comment by DD12-1916** [comment]
Oh I see, although I was almost a hundred percent sure that your character is instead immediately teleported, but it seems that I misremembered... hmm...
Anyway, thanks again for your response! I really do appreciate it

**Comment by henkelmax** [comment]
No problem!

**Comment by BluePhoenix0120** [comment]
for 1.12.2?
