### ISSUE TITLE
Corpses getting destroyed by dragons from Ice and Fire mod. 1.16.4

### ISSUE THREAD

**Issue by Oriansenshi** [henkelmax/corpse#31]
I run a multiplayer server and one of my players is having an issue with level 4 and 5 dragons being able to destroy her corpse and her losing her items. I have tried adding itemid corpse:corpse to the dragon destruction blacklist and it hasnt done anything. Is there any way i can make the corpse indestructible? or do i have the itemid wrong?

**Comment by henkelmax** [comment]
The corpse should be indestructible. The ID is right too. I would suggest reporting this to the Ice and Fire mod, since there is not much I can do about that.

**Comment by Oriansenshi** [comment]
will do, thank you for the prompt response

**Comment by henkelmax** [comment]
No problem!
