### ISSUE TITLE
Death History allows recovery of items outside of Creative with Quark

### ISSUE THREAD

**Issue by Malm6erg** [henkelmax/corpse#32]
The quark auto-extract feature allows (circled in the first image) allows you to take the inventory out of the Death History screen while in survival mode. 

![bug1](https://user-images.githubusercontent.com/14307055/112935302-1b9d3780-90e9-11eb-8b17-3d989a3c124e.png)
![bug2](https://user-images.githubusercontent.com/14307055/112935314-1fc95500-90e9-11eb-8062-91ac367c3c59.png)

**Comment by henkelmax** [comment]
Please report this bug to Quark. It seems that they are ignoring slots that the player can't take items out.
