### ISSUE TITLE
Corpse disappearing

### ISSUE THREAD

**Issue by rexlManu** [henkelmax/corpse#33]
**Bug description**
The corpse are random disappearing

**Versions**
Minecraft 1.16.5
Forge 36.0.58
Mod 1.0.1

**Other mods**
FTB Endeavour

So first, I hate myself to do this because im self a developer and know that its annoying to get a issue without crash / details.

But im trying to find other that maby find the same issue and im trying to make also some research but let me tell the issue:
I'm server owner of a small community of players for the modpack FTB Endeavour and I already had the problem that 3 players come to me and told me that they lost there stuff and the corpse was'nt here. I got the following details:
- It disappearing after they had a disconnection when they rmg the corpse
- After several dies they come back and then was gone

Im trying further more trying to reproduce the bug.

**Comment by henkelmax** [comment]
Please send me the log files.
Please also include the mods config.

**Comment by henkelmax** [comment]
Closed due to inactivity.
