### ISSUE TITLE
Config option to prevent OPs from bypassing settings

### ISSUE THREAD

**Issue by Gitberham** [henkelmax/corpse#34]
Right now, OPs can easily bypass the no looting rule when the corpse hasn't turned into a skeleton yet. I get this is useful for OPs to check for things regular players shouldn't have to check for, but some servers are strictly private meaning that it isn't necessary.

Could there be a seperate config option that disables the OP bypass?

**Comment by henkelmax** [comment]
I don't see why this would be useful. If you don't trust your OPs, maybe consider deoping them :D

**Comment by Gitberham** [comment]
This isn't a trust issue, this is to avoid potential mistakes from happening. We have armor sets in the game that make players look like skeletons, if you're an OP and are able to loot the corpse too early, it's easy to jump to the conclusion that they've already turned into a skeleton.
