### ISSUE TITLE
Corpses do not spawn.

### ISSUE THREAD

**Issue by Yucareux** [henkelmax/corpse#35]
**Please read the [FAQ](https://modrepo.de/minecraft/corpse/faq) before submitting a bug report!**

**Bug description**
The corpse wont spawn when getting killed, the player will just drop all items like vanilla minecraft. We run a server with some mods.

**Steps to reproduce the issue**
1. Install the mod on  a server
2. Kill the player.

**Expected behavior**
A corpse of the player should spawn.

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- 1.16.5
- Forge version: 36.1.4
- Mod version: 1.0.3

**Other mods**
Issue only occurs on the server, when playing on singleplayer the problem is gone.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Please provide your log files.

**Comment by Yucareux** [comment]
[latest.log](https://github.com/henkelmax/corpse/files/6328832/latest.log)

**Comment by Yucareux** [comment]
This is the server log

**Comment by henkelmax** [comment]
I can't find any issue with the mod in the config.
Can you please try if it happens without any other mods?

**Comment by Yucareux** [comment]
After testing looks like is an incompability with Mohist, which is a minecraft forge modification to run spigot, bukkit and Paper/Spigot/Bukkit

**Comment by henkelmax** [comment]
Yeah, these plugin mods always make problems. Unfortunately I can't do anything about that.
