### ISSUE TITLE
Corpse dissappears after interaction

### ISSUE THREAD

**Issue by debterr** [henkelmax/corpse#36]
**Please read the [FAQ](https://modrepo.de/minecraft/corpse/faq) before submitting a bug report!**

**Bug description**
I'm not the server owner, just a player, but I noticed while playing that sometimes there seems to be the chance of items not fully transferring to your body if you die while transferring, and by the time you get back to your death location again the other corpse is gone, and your newest corpse doesn't have any of the transferred things, thus losing your items. It's happened to me twice while playing on Engineer's Life 2 Modpack.

**Steps to reproduce the issue**
1. Die
2. Go to body
3. While at body die just after hitting transfer
4. Go back to body (other body is gone after the timeout, since the transfer button was pressed) but the new body doesn't have any of the items. Also it was a full inventory picture below from death history GUI.

**Expected behavior**
There should be some check to ensure that items were successfully transferred.

**Log files**
Can't access this I am not the server owner.

**Versions**
- Minecraft version: 1.16.5
- Forge version: forge-36.10
- Mod version: corpse-1.16.5-1.0.1.jar

**Other mods**
All the mods from Engineer's Life 2 (sorry I couldn't get curse to give me a list of the mods)

**Screenshots (Optional)**
Screenshots of the issue.

![image](https://user-images.githubusercontent.com/10887464/116005888-d4a64300-a5bd-11eb-8c85-ab03eceb756c.png)

**Comment by henkelmax** [comment]
Does this happen consistently?
If yes, how do you reproduce it?

**Comment by debterr** [comment]
I have not been able to reproduce it. Both times it has happened its been me doing the following.
1. Dying 
2. Respawn and run back to corpse
3. Try to press transfer but die while I am pressing.
4. By the time I get back to both corpses the first one is gone, and the second corpse has none of the items.

Forgive me I can't recreate it fully, and I wasn't recording at the time it happened. But it has happened twice, where all my items have ended up just "disappearing" all together.

**Comment by debterr** [comment]
Not sure if there is just an issue with the timing of how its happening, and I'm dying before the transfer is "complete" so the new corpse doesn't have the items, but the old corpse "thinks" it did and dissapears. But thats the only thing I can think of.

**Comment by henkelmax** [comment]
The transfer is happening instantly. This process can't be stopped halfway.

**Comment by henkelmax** [comment]
It should be fixed with the latest version.

**Comment by debterr** [comment]
Is it possible to be dead and still hit the transfer button due to the lag between server and client?
I can try to load up just that mod on a server.. but I can only do it on my local computer so there would be no chance of lag between client and server in that instance.

Also okay I will talk with the server owner and see if he can update that to the latest version.

**Comment by henkelmax** [comment]
> Is it possible to be dead and still hit the transfer button due to the lag between server and client?

Yeah, I'm assuming that exactly that was happening
