### ISSUE TITLE
Item dropping outside corpse and not stay inside

### ISSUE THREAD

**Issue by CormacZ** [henkelmax/corpse#39]
![image](https://user-images.githubusercontent.com/71203678/116229409-0d464800-a789-11eb-8d4e-034496698188.png)
https://www.curseforge.com/minecraft/mc-mods/corpse/files/3226498
idk why it do that

**Comment by henkelmax** [comment]
Please fill out the whole bug template.

**Comment by js240627** [comment]
I'm having the same problem. When the player died, all the items drop out the corpse.
