### ISSUE TITLE
When a player dies, the items don't go inside his body

### ISSUE THREAD

**Issue by Teoxex** [henkelmax/corpse#43]
**Bug description**
When a player dies on my Modded Minecraft Server, the items are scattered around and not inside the body. Only the Curios API charms remain. Could you tell me why?

**Steps to reproduce the issue**
1. Kill a Player
2. Items are scattered around while the body is generated but empty (or with the charms of the Curios API)

**Expected behavior**
Items should remain inside the body (armor, tools and more)

**Log files**
Server Log: https://gist.github.com/Teoxex/69f5ff90a09193318db1c9a98e4eb2db
Client Log: 

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.1.16
- Mod version: [1.16.4] Corpse 1.16.4-1.0.6
- Server: Mohist version 1.16.5-545 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.1.16)

**Other mods**
https://haste.mohistmc.com/iciyujamuy.apache

**Screenshots**
https://i.imgur.com/ViJzunZ.png

**Comment by henkelmax** [comment]
Sorry, but I don't support plugins.

**Comment by DisplayPort** [comment]
This was fixed by Mohist, check my comment in #46
