### ISSUE TITLE
Crash upon Death

### ISSUE THREAD

**Issue by Enethim** [henkelmax/corpse#44]
**Please read the [FAQ](https://modrepo.de/minecraft/corpse/faq) before submitting a bug report!**

**Bug description**
I die game dies, world gets corrupted & further attempts to join in it results in crash.

**Steps to reproduce the issue**
1. Die

**Log files**
https://pastebin.com/eeQ5yKYa
(all the errors point to corpse mod)

**Versions**
- Minecraft version **1.16.5**
- Forge version Latest  **36.1.16**
- Mod version Latest as **all of them**

**Other mods**
Using Mod-pack "Medieval Minecraft [Forge]
https://www.curseforge.com/minecraft/modpacks/medieval-minecraft-fabric
Upon further inspection from mod-pack author I was directed here.
(all the errors point to corpse mod)

**Screenshots (Optional)**
No need.

**Comment by henkelmax** [comment]
Please check if it happens without optifine.

**Comment by Enethim** [comment]
> Please check if it happens without optifine.

Yes it does.

**Comment by henkelmax** [comment]
Can you send me the logs of that?

**Comment by Enethim** [comment]
> Can you send me the logs of that?

https://pastebin.com/9M6SM53Z

**Comment by henkelmax** [comment]
Can you please try if it happens without any other mods at all? I am not able to reproduce this issue.
If it works for you without other mods, please reduce the mods to the mod that causes the crash.

**Comment by GoliathX211** [comment]
It might be coincidence that the modpack is created by the same author as the Better Minecraft [Forge] modpack that I am having server issues with.

**Comment by henkelmax** [comment]
Closed due to inactivity
