### ISSUE TITLE
Enable/disable config option

### ISSUE THREAD

**Issue by Sm0keySa1m0n** [henkelmax/corpse#48]
A simple server config option to disable corpses would be nice - I have certain servers on my modpack in which I'd like to not have any corpses but on others I do.

**Comment by henkelmax** [comment]
The whole purpose of the mod are corpses. Disabling it in the config would be just the equivalent of just removing the mod.

**Comment by Sm0keySa1m0n** [comment]
Not if you are creating a server for a specific modpack but on your server you don't want corpses?

**Comment by henkelmax** [comment]
I'm sorry, but this is too specific to add an option for this into the mod.
