### ISSUE TITLE
Player's corpse and death history is not spawning

### ISSUE THREAD

**Issue by Muttculture** [henkelmax/corpse#49]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/corpse/faq)!**

Hello, I have a player on my server who is experiencing some issues with the mod, she's the only player experiencing this. Her bodies are showing up with no items, and her death history is gone. Do we have a fix for this?

**Comment by henkelmax** [comment]
Are you using plugins on your server?

**Comment by Muttculture** [comment]
No, we have a mix of datapacks and mods we're using, no plugins

**Comment by Muttculture** [comment]
We've used the corpse mod with alot of the same mods/datapacks and it's never done this before

**Comment by henkelmax** [comment]
Can you send me the server logs of this happening?

Can you also try if it happens without any other mods?

**Comment by henkelmax** [comment]
Closed due to inactivity
