### ISSUE TITLE
Epic fight/Corpse freeze

### ISSUE THREAD

**Issue by Trueking3T** [henkelmax/corpse#52]
**Please read the [FAQ](https://modrepo.de/minecraft/corpse/faq) before submitting a bug report!**

**Bug description**
Game freeze after dying in any way 

**Steps to reproduce the issue**
1. logging world
2. Dying in any way
3. Game freeze

**Expected behavior**
Respawn to spawn point

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).
https://gist.github.com/Trueking3T/b365dec0f2a0432615d5e6adb4db6b1f#file-epic-fight-gitch

**Versions**
- Minecraft version : 1.16.5
-Forge version : 36.1.18
-Mod version :  corpse-1.16.5-1.0.5

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.
EpicFightMod-1.16.5-4.1.3

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Does this just happen in combination with the epic fight mod?

**Comment by Trueking3T** [comment]
Yes

**Comment by henkelmax** [comment]
Can you test if it happens without the corpse mod.

**Comment by Trueking3T** [comment]
Corpse mod work prefectly without epic fight

**Comment by Trueking3T** [comment]
Corpse mod works by it self

**Comment by henkelmax** [comment]
No I mean if it happens without it.

**Comment by Trueking3T** [comment]
No it doesn't

**Comment by henkelmax** [comment]
So it only happens with both mods in combination?
Can you please post this issue also on their issue tracker?

**Comment by Trueking3T** [comment]
Yeah it only with the two mod and yeah post it they issues  tracker

**Comment by josesobral22005813** [comment]
I am having the same problem, although the game crashes, it doesnt create a log in the crash-reports folder, and when I go back to the save that crashed, the game simply rollsback to around 30s-60s before the death

**Comment by zoyer2** [comment]
same here

**Comment by zoyer2** [comment]
1.16.5 with the latest version

**Comment by chrisalo97** [comment]
I'm having the same issue, I was not able to even join again the server. I had to remove the epic fight mod and I could join again with no issues.

**Comment by Yesssssman** [comment]
Hello, I'm creator of epicfight mod.

I recently found this problem is occured by infinite loop.

at de.maxhenkel.corpse.entities.DummyPlayer.getDimensions(DummyPlayer.java:36)
> @Override
> public EntityDimensions getDimensions(Pose pose) {
>     return new EntityDimensions(super.getDimensions(pose).width, Float.MAX_VALUE, true);
> }

You set DummyPlayer's size Float.MAX_VALUE. I don't know why you set it like this, but if you say it's necessary, I'll find another way to avoid this issue.

**Comment by henkelmax** [comment]
This is set to such a high value to avoid the nameplate from displaying. Would this freeze still occur if I would set it to a value like 1000?

**Comment by Yesssssman** [comment]
What about using RenderNameplateEvent? Is it still displays after canceling this event?

**Comment by henkelmax** [comment]
I don't remember. Maybe this wasn't a thing back then. I will take a look at it.

**Comment by henkelmax** [comment]
It should be fixed in the next version. Please let me know if it works.

**Comment by EkutoruSama** [comment]
I have test the new version 1.0.6 and it´s Working :D 
Thank you very much <3
