### ISSUE TITLE
DUPED bug 1.16.5!

### ISSUE THREAD

**Issue by XionioXMaster** [henkelmax/corpse#53]
**Please read the [FAQ](https://modrepo.de/minecraft/corpse/faq) before submitting a bug report!**

**Bug description**
CAREFULLY DUPED! I found a creepy error due to which you can cheat shulkers and maybe other things, to do this after death, press U, then go to the things of the last death, hold SHIFT + F and press the right and left mouse buttons on the shulker until open his inventory, everyone will hit him, take 2 shulkers from the corpse! **Mohist core**

**Steps to reproduce the issue**
Video: https://youtu.be/pl92dHcgxn0

**Log files**
nope

**Versions**
- Minecraft version 1.16.5
- Forge version last 1.16.5
- Mod version  1.0.5

**Other mods**
nope

**Comment by henkelmax** [comment]
This mod is not compatible with mohist.
