### ISSUE TITLE
Dupe Glitch with Quark Mod

### ISSUE THREAD

**Issue by SharkieTV** [henkelmax/corpse#55]
**Bug description**
When you die you can check your death history with U and check your items but when you have quark installed it has a extract function where you basically can infinitely extract a backpack with curious.
Video: https://www.youtube.com/watch?v=QRH3dJTbjt8

**Steps to reproduce the issue**
1. Click U a& Open Death History
2. Click Items
3. Click Extract 

**Expected behavior**
Not being able to extract

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.1.31
- Mod version: [1.16.5] Corpse 1.16.5-1.0.5

**Other mods**
Quark

**Screenshots (Optional)**
Video: https://www.youtube.com/watch?v=QRH3dJTbjt8

Lmk if I need to report this to Quark instead which they probs wont fix anytime soon

**Comment by henkelmax** [comment]
This is a quark bug. The transfer item button does not check if you are able to take the item. I would recommend excluding this GUI in the config.

**Comment by henkelmax** [comment]
Look at their documentation.
