### ISSUE TITLE
Error Corpse mod pressing keys

### ISSUE THREAD

**Issue by mobby45** [henkelmax/corpse#57]
**Bug description**
i was playing, i'm dead in the nether so i press my key for watch the corpse and it crash

**Steps to reproduce the issue**
1. install all the mods, with the forge version
2. Click on play, for launch the game
3. See the error in the crash reports

**Expected behavior**
i was playing, i'm dead in the nether so i press my key for watch the corpse and it crash

**Log files**
https://gist.github.com/mobby45/61a48331e83e79408591086df1856997

**Versions**
- 1.12.2
- 14.23.5.2854
- corpse-1.12.2-1.0.3

**Other mods**
Advanced Rocketry
Alchemistry
Alib
Aroma1997Core
Aroma Dimensional World
Aunis
Autocrafter
Bonsai Trees
CodeChickenLib
CofhCore
CofhWorld
corpse
DeepResonance
ElecCore
ExtraUtils
Forgelin
hbm
hwyla
ICBM
IchunUtil
JEI
LibVulpes
mcjtylib
NotEnoughItem
Optifine
RedstoneFlux
Sync
ThermalFoundation
ThermalExpansion
ThermalDynamics
TheVicraft AUnis addon
WailaHarvestability
ZPM

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/68152858/127781502-f068e1b8-4698-4400-a5f9-d5b192df1b10.png)

**Comment by henkelmax** [comment]
Version 1.12 is no longer supported.
