### ISSUE TITLE
[1.16.2-1.0.8] Death Screen does not resize to fit longer dimension names

### ISSUE THREAD

**Issue by TelepathicGrunt** [henkelmax/corpse#6]
When using dimension mods such as the Bumblezone, the Corpse's death screen will not resize to fit the longer dimension name and causes it to merge with the 'Dimension' text. That's it lol. Should be easily reproducible. 

Also, with a bit of string manipulation, you could easily show "the_nether" as "The Nether" and "the_bumblezone" as "The Bumblezone". I did get a bug report for my mod saying that the dimension name wasn't pretty in Corpse lol. I had to break the news that there wasn't any standardized way of getting dimension names as Mojang never added them to the en_us.js file. If you decide not to do the string manipulation, just let me know if you add an alternate way for players or dimension mods to say how to display dimension names. :)

![image](https://user-images.githubusercontent.com/40846040/92517161-37d89600-f1e4-11ea-9812-b8e18e4f908d.png)

**Comment by henkelmax** [comment]
Should be fixed in the latest version
