### ISSUE TITLE
Compatability with Pehkui (Scaled players)

### ISSUE THREAD

**Issue by netcore10** [henkelmax/corpse#61]
**Is your feature request related to a problem? Please describe.**
I think that compatibility with pehkui would be really cool! Currently, the corpse is defaulted to normal size (as it should, of course)

**Describe the solution you'd like**
Having the corpse the same size as the size set from the pehkui mod (Each player can be set to a different size) would be a great feature!

**Describe alternatives you've considered**
A command to tie a corpse size to a player instead, as an alternative?

**Additional context**
I'm an avid enjoyer of roleplay and story, currently working on a small community mod pack, having a scalable corpse would be something very immersive with the two mods together.

**Comment by henkelmax** [comment]
This wouldn't work well with the corpses hitbox.
I also don't plan to add compatibility with other mods, sorry.
