### ISSUE TITLE
[Question] the corpse is not spawned correctly when death location is under y 0

### ISSUE THREAD

**Issue by rsta79** [henkelmax/corpse#63]
**Please read the [FAQ](https://modrepo.de/minecraft/corpse/faq) before submitting a bug report!**

**Bug description**
When the player's death position y < 0, the corpse is not spawned correctly,
if the player's death position y < 0, the corpse will be spawned at y 0.

**Steps to reproduce the issue**
1. death under y 0
2. the corpse will be spawned at y 0

**Expected behavior**
The corpse should be spawned at the exact location when the player died

**Log files**
Skip

**Versions**
- Minecraft version 1.17.1
- Forge version forge-1.17.1-37.0.82
- Mod version 1.0.4

**Other mods**
Skip

**Screenshots (Optional)**
Skip

**Comment by henkelmax** [comment]
Thats not a bug thats a frature. You can disable that in the config.
