### ISSUE TITLE
Crash When Pressing Key

### ISSUE THREAD

**Issue by xDarkSoulGr** [henkelmax/corpse#67]
So... i moved from 1.12.2 to 1.16.5 and after i press U to see the death history my minecraft crashes (and im not the only one this happens to my friends too) in the crash report i get this error:
![Screenshot 2021-10-31 221137](https://user-images.githubusercontent.com/93491811/139599749-55538fcc-ca1a-4355-9ccc-f3d446d15fda.png)
 do u know how to fix this? i tried reinstalling the mod in the server and it still crashes.

**Comment by henkelmax** [comment]
Please follow the bug template
