### ISSUE TITLE
No config file.

### ISSUE THREAD

**Issue by Chann3l-Chas3r** [henkelmax/corpse#68]
**Please read the [FAQ](https://modrepo.de/minecraft/corpse/faq) before submitting a bug report!**

**Bug description**
There is no config file for this mod. (Note: I had made a comment on the Forge page for this mod that corpses weren't despawning at all after looting them, but it turns out that I just hadn't stayed in the area long enough for enough time to pass. I had been under the impression that the default was instant-despawn so I had assumed they were broken.)

**Steps to reproduce the issue**
I downloaded the mod. When I went to the 'config' folder about a day later to fiddle with the settings, there was no config file for this mod.

**Expected behavior**
I expected there to be a config file.

**Log files**
https://gist.github.com/Chann3l-Chas3r/004b40eead80eecfb22fbcbcb000416c

**Versions**
- Minecraft: 1.16.5
- Forge: 1.16.5-forge-36.2.0
- Mod: corpse-1.16.5-1.0.6

**Other mods**
I just started modding and I downloaded all 93 mods I'm using at the same time. That's a lot of typing so I just copied them to a Google Drive folder: https://drive.google.com/drive/folders/13DB53UEbXufQdy6Fdif_vH86ujsJoKnf?usp=sharing

**Screenshots (Optional)**
https://imgur.com/a/hdu3ilP

**Comment by henkelmax** [comment]
The config isn't located in the config folder. Read the FAQ for more information.
