### ISSUE TITLE
Corpse spawns in y level below 0

### ISSUE THREAD

**Issue by legitswitch** [henkelmax/corpse#70]
**Bug description**
Corpse spawns in void, even when config has this option disabled:
fall_into_void = false

**Steps to reproduce the issue**
1. Travel very fast in overworld.
2. Fall into void from chunks not loading fast enough.
3. Die from void.
4. Corpse shows negative y-coordinate.

**Expected behavior**
Corpse should spawn above y=0.

**Log files**
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.2.8
- Mod version: 1.0.6
- Modpack: Create: Above and Beyond

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/88232383/142121341-f990b2cf-c921-4d2d-8e17-6ab6e7aa5975.png)

**Comment by henkelmax** [comment]
I need your logs.

**Comment by GoliathX211** [comment]
I had this issue on another server but didn't think anything of it. When the admins has checked from when I died in the overworld to the void at negative ~10000 they restored the inventory. One admin teleported to the coordinates of the body in X and Z where the body was floating under the bedrock. The player death history screens does not show the current coordinates of your body, but rather where you had died.

**Comment by henkelmax** [comment]
The death coordinates never show your corpses location. It shows the location where you died.

**Comment by henkelmax** [comment]
Closed due to inactivity.
