### ISSUE TITLE
Corpse disappearing 

### ISSUE THREAD

**Issue by nosiah26** [henkelmax/corpse#71]
Corpse disappearing and cannot be found using the player death history ("U")
The server is hosted on Aternos (https://aternos.org/server/)

2 instances
https://www.curseforge.com/minecraft/mc-mods/paragliders 
Died from fall damage while paragliding

https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons
Died from an Ice dragon

When we viewed the player death history, it only has some of our dated inventory a while back, not the current ones where we died (ex: Diamond Gear instead of Netherite Gear)

The only feature we had in common was the Grave Pet from Inventory pets (https://www.curseforge.com/minecraft/mc-mods/inventory-pets)
What caused this, and is the Grave Pet with the corpse mod a known issue or is there anything I can do?

![Grave Pet](https://user-images.githubusercontent.com/90959372/142752597-7f125d33-46a1-4595-9bd5-22ce1f2f4ca2.PNG)

**Comment by henkelmax** [comment]
You can't use two death processing mods at the same time, this will never work!

**Comment by SenpaiSamaSS** [comment]
> You can't use two death processing mods at the same time, this will never work!


I have the same issue of the body dissapearing but I don't have any other mod of death processing.
