### ISSUE TITLE
[FABRIC] 1.18 DOWNLOAD

### ISSUE THREAD

**Issue by SuryaRajgor** [henkelmax/corpse#72]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/corpse/faq)!**

Hello I can't find the download file for Fabric and in and I show in the FAQ about Fabric config

So it's available for fabric ??

**Comment by henkelmax** [comment]
Nonit isn't. The general section in the FAQ is the same for every mod.
