### ISSUE TITLE
Switched to Spectator upon death

### ISSUE THREAD

**Issue by carbondog** [henkelmax/corpse#74]
**Please read the [FAQ](https://modrepo.de/minecraft/corpse/faq) before submitting a bug report!**

**Bug description**
For the most part the mod was working great, but the last two deaths on my server caused the player to go into spectator mode. We had to have an admin switch them back to survival mode.

**Steps to reproduce the issue**
1. Die while in survival mode

**Expected behavior**
When a player dies, they should just respawn like normal and stay on survival mode

**Log files**
attached the latest log file. It happened twice today

**Versions**
- Minecraft version 1.18
- Forge version 1.18-38.0.15
- Mod version 1.18-1.0.2

**Other mods**
balm-2.3.0+0
FastLeafDecay-27.
netherportalfix-forge-1.18-9.0.0

[latest.log](https://github.com/henkelmax/corpse/files/7740139/latest.log)

**Comment by henkelmax** [comment]
Please try if this happens without any other mod.

**Comment by henkelmax** [comment]
Closed due to inactivity.
