### ISSUE TITLE
Corpse summons friezes

### ISSUE THREAD

**Issue by MineCinema** [henkelmax/corpse#75]
** Please read the [FAQ] (https://modrepo.de/minecraft/corpse/faq) before submitting a bug report! **

** Bug description **
Mod version corpse-1.12.2-1.0.8
On the server, when I kill a player, a freeze sometimes occurs. I have a freeze and a player whom I killed. Then the freeze passes and everything is fine again.
Writes in the server console at the moment of the freeze
[Server thread / WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class de.maxhenkel.corpse.entities.EntityCorpse from class de.maxhenkel.corpse.entities.EntityCorpseInventoryBase

** Steps to reproduce the issue **
Install mod on server, i used vanilla and catserver

** Log files **
There is nothing in the logs except what I showed you on the server console

** Versions **
- 1.12.2
- Forge 14.23.5.2859
- 1.0.8

** Other mods **
modularwarfare
With or without mod, corpses freeze happens.

** Screenshots (Optional) **
Screenshots of the issue.

**Comment by henkelmax** [comment]
This is completely normal, since the game needs to load the players skin.
This will not be fixed, since the 1.12.2 version is not under active development anymore.
