### ISSUE TITLE
Tilted cape in the Player Death History

### ISSUE THREAD

**Issue by Regnander** [henkelmax/corpse#76]
**Please read the [FAQ](https://modrepo.de/minecraft/corpse/faq) before submitting a bug report!**

**Bug description**

I think that having the cape of a player corpse hanging at an angle is a nice touch. However, the cape in the Player Death History is _also_ hanging at an angle, even though the player model is standing upright compared to the lying corpse.

**Steps to reproduce the issue**
1. Enter any world.
2. Run the `kill` command to create a corpse of yourself.
3. Open the player death history using the U key.
3. Look at the tilted cape of the player model.

**Expected behavior**

I expected the cape to hang straight down in the Player Death History instead of at an angle as if the cape is defying gravity.

**Log files**

None

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.2.22
- Mod version: 1.16.5-1.0.6

**Other mods**

No other mods

**Screenshots (Optional)**

![a](https://user-images.githubusercontent.com/17113053/147855057-82317115-400e-4570-8ba4-9318400bbe3d.png) ![b](https://user-images.githubusercontent.com/17113053/147855056-8fe17233-1e22-43bc-ac79-857dae63334d.png)

**Comment by henkelmax** [comment]
Does this also happen in 1.17+?

**Comment by Regnander** [comment]
> Does this also happen in newer mod versions (1.17+)?

This also happens on Forge 37.1.1 + corpse-1.17.1-1.0.5.jar and Forge 39.0.9 + corpse-1.18.1-1.0.0.jar.

However, on 1.18.1 the cape is (for the lack of better words) "leaning backwards" while retaining the same angle I reported:
![2022-01-01_18 07 06](https://user-images.githubusercontent.com/17113053/147856926-61110c9a-6be2-45e7-b418-139031eb4b9f.png)

This is also present in the GUI:
![2022-01-01_18 52 18(1)](https://user-images.githubusercontent.com/17113053/147857281-1d1d8736-d182-4b15-a612-dac34444090f.png) ![2022-01-01_18 52 24(1)](https://user-images.githubusercontent.com/17113053/147857280-591d4b3c-8d01-4a9b-8d1e-025684b00657.png)
