### ISSUE TITLE
Second skin layer and cape is not visible upon world reload

### ISSUE THREAD

**Issue by Regnander** [henkelmax/corpse#77]
**Please read the [FAQ](https://modrepo.de/minecraft/corpse/faq) before submitting a bug report!**

**Bug description**

The cape and the second layer of the player skin is not visible on a player corpse upon reloading a world.

**Steps to reproduce the issue**
1. Enter any world.
2. Use the `kill` command to create a corpse.
3. Exit the world.
4. Load the same world.
5. The corpse will no longer have the second skin layer or the cape.

**Expected behavior**

I expected my player corpse to be displayed the same way as it did when I exited my world. 

**Log files**

None

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.2.22
- Mod version: 1.16.5-1.0.6

**Other mods**

None

**Screenshots (Optional)**

| Before reload | After reload |
|-|-|
| ![2022-01-01_17 29 49](https://user-images.githubusercontent.com/17113053/147855243-d572a12c-8552-4cf9-8405-99ba26ded807.png) | ![2022-01-01_17 30 01](https://user-images.githubusercontent.com/17113053/147855248-bdde9020-0d9e-45a0-98f1-f73c0b560cdd.png) |

**Comment by henkelmax** [comment]
Does this also happen in newer mod versions (1.17+)?

**Comment by Regnander** [comment]
> Does this also happen in newer mod versions (1.17+)?

This also happens on Forge 37.1.1 + corpse-1.17.1-1.0.5.jar and Forge 39.0.9 + corpse-1.18.1-1.0.0.jar.

**Comment by henkelmax** [comment]
Alright, thanks
