### ISSUE TITLE
Compability with Relics mod

### ISSUE THREAD

**Issue by MiniRaptor** [henkelmax/corpse#84]
It would be very convenient and cool if the mod had compatibility with Relics, because it is inconvenient to manually put on the loot every time.

Mod: https://www.curseforge.com/minecraft/mc-mods/relics-mod

**Comment by henkelmax** [comment]
I already stated this several times. There won't me support for custom inventory slots.

**Comment by MiniRaptor** [comment]
Oh, sorry then for taking your time
