### ISSUE TITLE
Can't open Death History

### ISSUE THREAD

**Issue by NurarihyonMaou** [henkelmax/corpse#86]
So... my Corpse dissapeared before I got to it's location, even tho the earlier one is still there...
And I can't open Death History, tried different Binds, but nothing works (when I click the Bind - Nothing Happens, Command - same behaviour as Bind)

I'm using this ModPack - https://www.modpackindex.com/modpack/43037/elden

**Comment by henkelmax** [comment]
The death history might not be available in the mod version you are using.

**Comment by NurarihyonMaou** [comment]
> The death history might not be available in the mod version you are using.

any way to retrieve my items??

**Comment by henkelmax** [comment]
The file should be saved in your world folder in `deaths`

**Comment by NurarihyonMaou** [comment]
> The file should be saved in your world folder in `deaths`

what I'm supposed to do with it??

**Comment by henkelmax** [comment]
You can read the NBT data

**Comment by NurarihyonMaou** [comment]
> You can read the NBT data

Thank You
