### ISSUE TITLE
BUG: Lightmans Currency Mod conflict

### ISSUE THREAD

**Issue by K4N0** [henkelmax/corpse#88]
Minecraft Version (REQUIRED): 1.18.1
Forge Version (REQUIRED): forge-1.18.1-39.1.2
Lightman's Currency Version (REQUIRED): lightmanscurrency-1.18-1.0.5.3.jar
Corpse Version (REQUIRED): corpse-1.18.1-1.0.4.jar
Other Relevant Mods & Version (LC Tech, etc.): Modpack: https://www.curseforge.com/minecraft/modpacks/cataclysm-zombie-apocalypse
Connection Type (Single-player, server/client, LAN world): Modpack comes with a server IP

**Bug description**
I am attempting to keep the wallet from dropping when a player dies. I have enabled gamerule keepWallet. 
When a player dies, the wallet remains on the player in the wallet slot, but the coins are pulled out of it.

"Lightmans Currency" Mod Conflict
Lightmans Currency Mod: https://www.curseforge.com/minecraft/mc-mods/lightmans-currency

**To Reproduce**
1. Install both lightmans and corpse mod
2. enable gamerule keepwallet
3. die
4. wallet does not drop, but the coins get pulled out of the wallet

**Expected behavior**
It would be nice if the coins would stay in the wallet upon death.
I understand this may be an issue on their end and I have taken the liberty of creating an issue on their end as well.

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version
- Forge version
- Mod version

**Other mods** Modpack link up above
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by K4N0** [comment]
https://github.com/Lightman314/LightmansCurrency/issues/43

**Comment by henkelmax** [comment]
Closed due to inactivity (https://github.com/Lightman314/LightmansCurrency/issues/43#issuecomment-1072795173)
