### ISSUE TITLE
Enable PvP Mode in some areas

### ISSUE THREAD

**Issue by K4N0** [henkelmax/corpse#89]
**Is your feature request related to a problem? Please describe.**

There is no Problem, but It would be nice if we could set an Area for PvP.
Currently a corpse never despawns and only the owner is able to get their items back from the corpse during a 24hr period.
This is because we have a zombie apocalypse modpack where players will team and die quite often.
Problem: In our PvP area, a user would have to Camp a body for 24hrs to get the loot.
The way it's setup now works well for our non pvp world, but we could use a PvP world or area where the corpse is disabled.

**Describe the solution you'd like**
The ability to have an a designated area PvP where the corpse is lootable by anyone without a wait time.
OR
The ability to setup a world where the corpse is disabled.

**Describe alternatives you've considered**
Just those 2. 

**Additional context**

**Comment by henkelmax** [comment]
Just kill the entities in that radius with a command block.
Such a feature won't be added as an option.

**Comment by K4N0** [comment]
Apologies for the misunderstanding,
I meant we don't have a problem with bodies de-spawning, our issue is we want the players items to drop on the ground.

**Comment by henkelmax** [comment]
Yes i understood that.

Just kill the corpse with a command or set the despawn timer really low woith a command block and the items will drop to the ground.
