### ISSUE TITLE
When the corpse wears the equipment of the custom model, the corpse cannot be displayed normally.

### ISSUE THREAD

**Issue by IXBOB** [henkelmax/corpse#93]
**Bug description**
When the corpse wears the equipment of the custom model, the corpse cannot be displayed normally.
(for example: mekasuit armor in the famous mod MEKANSIM

**Steps to reproduce the issue**
1. wear mekasuit armor before you death.
2. kill yourself in anyway.
3. If you wear a whole set of armor, you can't find your corpse. If you wear part of your armor, the corresponding part of your corpse will disappear.

**Expected behavior**
The armor will display correctly and give the corpse a custom model

**Versions**
- 1.16.x
- Forge Version-(May be in each version)
- Mod Version-(May be in each version)

**Other mods**
Mekansim

**Comment by henkelmax** [comment]
Works perfectly fine:
![image](https://user-images.githubusercontent.com/13237524/167242873-0f460219-5afd-48ab-97e5-9d0ff637b475.png)
