### ISSUE TITLE
Animated corpses

### ISSUE THREAD

**Issue by hakanai** [henkelmax/corpse#98]
If the player is killed by a Zombie (including Drowned, Husks and other variants), spawn an Animated Corpse mob at that position.

Animated Corpse has
- all the behaviour of a Zombie
- the same health as the player who died, including any extra hearts
- the same armour as the player who died
- the appearance of the player's corpse, as appropriate for how long it has been dead

Animated Corpse weilds whatever item was equipped at the player's death.

When Animated Corpse dies, it spawns a regular Corpse. Ideally, seamlessly.

**Comment by henkelmax** [comment]
Sorry but that won't be a thing. Having an entity thwt wanders around would make players lose their items, since they wouldn't find it at their original spot. It would also allow other players to troll you by luring the entity away, so you can't find it anymore.
